const ManagerList = [
  { id: 1, manager: "Brantley Olland" },
  { id: 2, manager: "Carlota Cutten" },
  { id: 3, manager: "Anson Gartsyde" },
  { id: 4, manager: "Winna Tureville" },
  { id: 5, manager: "Sari Mileham" },
  { id: 6, manager: "Lindsey Goodlake" },
  { id: 7, manager: "Desiree Giorgi" },
  { id: 8, manager: "Mitch Beran" },
  { id: 9, manager: "Jaime Mayworth" },
  { id: 10, manager: "Celeste Chanter" },
  { id: 11, manager: "Fifi Walne" },
  { id: 12, manager: "Conrad Humphrey" },
  { id: 13, manager: "Xylia McKinless" },
  { id: 14, manager: "Annie Whyler" },
  { id: 15, manager: "Brewer Peach" },
  { id: 16, manager: "Aloysius Kasbye" },
  { id: 17, manager: "Immanuel Riches" },
  { id: 18, manager: "Casey Greest" },
  { id: 19, manager: "Alejandro Tordoff" },
  { id: 20, manager: "Constantine Pudney" },
  { id: 21, manager: "Frankie Matsell" },
  { id: 22, manager: "Kaleb Whawell" },
  { id: 23, manager: "Mimi Addie" },
  { id: 24, manager: "Filippo Heathfield" },
  { id: 25, manager: "Tracee Aries" },
  { id: 26, manager: "Whitney Durrand" },
  { id: 27, manager: "Ruthanne Fulop" },
  { id: 28, manager: "Shay Hartly" },
  { id: 29, manager: "Felicle Jerome" },
  { id: 30, manager: "Rikki Topper" }
];

export default ManagerList;
