import icon_employee_profile from "../../assets/images/employees/icon_employee_profile.png"

const EmployeeCardList = 

// [
//     {
//         id:1,
//         pfp: icon_employee_profile,
//         emp_id:" "103",
//         emp_name: "Bernardo Galavis",
//         emp_mail: "bernardo.g@piktorlabs.com",
//         emp_role: "Web Developer",
//         emp_mob: "9876323210",
//         emp_date: "Jan 1, 2020", emp_manager:"",
//     },
//     {
//         id:2,
//         pfp: icon_employee_profile,
//         emp_id:" "102",
//         emp_name: "Ruby Pen",
//         emp_mail: "Ruby.p@piktorlabs.com",
//         emp_role: "Front End Developer",
//         emp_mob: "9876123210",
//         emp_date: "Jan 1, 2020", emp_manager:"",
//     },
//     {
//         id:3,
//         pfp: icon_employee_profile,
//         emp_id:" "101",
//         emp_name: "Theon Grey",
//         emp_mail: "Grey.theon@piktorlabs.com",
//         emp_role: "UX Designer",
//         emp_mob: "1376543210",
//         emp_date: "Jan 1, 2020", emp_manager:"",
//     },
//     {
//         id:4,
//         pfp: icon_employee_profile,
//         emp_id:" "100",
//         emp_name: "Ariana Grande",
//         emp_mail: "Ariana.g@piktorlabs.com",
//         emp_role: "Data Scientist",
//         emp_mob: "9876543210",
//         emp_date: "Jan 1, 2020", emp_manager:"",
//     },
//     {
//         id:5,
//         pfp: icon_employee_profile,
//         emp_id:" "99",
//         emp_name: "Emma Watson",
//         emp_mail: "Emma@piktorlabs.com",
//         emp_role: "Product Manager",
//         emp_mob: "9876509210",
//         emp_date: "Jan 1, 2020", emp_manager:"",
//     },
//     {
//         id:6,
//         pfp: icon_employee_profile,
//         emp_id:" "98",
//         emp_name: "Rebecca James",
//         emp_mail: "Rebeccajames@piktorlabs.com",
//         emp_role: "Interaction Designer",
//         emp_mob: "9828543210",
//         emp_date: "Jan 1, 2020", emp_manager:"",
//     },
//     {
//         id:7,
//         pfp: icon_employee_profile,
//         emp_id:" "97",
//         emp_name: "Tania Rai",
//         emp_mail: "Tania@piktorlabs.com",
//         emp_role: "Data Analyst",
//         emp_mob: "9666543210",
//         emp_date: "Jan 1, 2020", emp_manager:"",
//     },
//     {
//         id:8,
//         pfp: icon_employee_profile,
//         emp_id:" "96",
//         emp_name: "Thomas Green",
//         emp_mail: "Thomasgreen@piktorlabs.com",
//         emp_role: "Software Engineer",
//         emp_mob: "9876543210",
//         emp_date: "Jan 1, 2020", emp_manager:"",
//     },
//     {
//         id:9,
//         pfp: icon_employee_profile,
//         emp_id:" "95",
//         emp_name: "Emily Clarke",
//         emp_mail: "Emily clarke@piktorlabs.com",
//         emp_role: "Web Developer",
//         emp_mob: "3476543210",
//         emp_date: "Jan 1, 2020", emp_manager:"",
//     },
//     {
//         id:10,
//         pfp: icon_employee_profile,
//         emp_id:" "94",
//         emp_name: "Summer Simpson",
//         emp_mail: "Summersimpsons@piktorlabs.com",
//         emp_role: "Web Developer",
//         emp_mob: "5676543210",
//         emp_date: "Jan 1, 2020", emp_manager:"",
//     },
//     {
//         id:11,
//         pfp: icon_employee_profile,
//         emp_id:" "93",
//         emp_name: "James White",
//         emp_mail: "James.w@piktorlabs.com",
//         emp_role: "Web Developer",
//         emp_mob: "1236543210",
//         emp_date: "Jan 1, 2020", emp_manager:"",
//     },
//     {
//         id:12,
//         pfp: icon_employee_profile,
//         emp_id:" "92",
//         emp_name: "Bernardo Galavis",
//         emp_mail: "bernardo.g@piktorlabs.com",
//         emp_role: "Web Developer",
//         emp_mob: "9996543210",
//         emp_date: "Jan 1, 2020", emp_manager:"",
//     },
//     {
//         id:13,
//         pfp: icon_employee_profile,
//         emp_id:" "91",
//         emp_name: "Ruby Pen",
//         emp_mail: "Ruby.p@piktorlabs.com",
//         emp_role: "Front End Developer",
//         emp_mob: "9876543210",
//         emp_date: "Jan 1, 2020", emp_manager:"",
//     },
//     {
//         id:14,
//         pfp: icon_employee_profile,
//         emp_id:" "90",
//         emp_name: "Theon Grey",
//         emp_mail: "Grey.theon@piktorlabs.com",
//         emp_role: "UX Designer",
//         emp_mob: "9876543210",
//         emp_date: "Jan 1, 2020", emp_manager:"",
//     },
//     {
//         id:15,
//         pfp: icon_employee_profile,
//         emp_id:" "89",
//         emp_name: "Ariana Grande",
//         emp_mail: "Ariana.g@piktorlabs.com",
//         emp_role: "Data Scientist",
//         emp_mob: "9876543210",
//         emp_date: "Jan 1, 2020", emp_manager:"",
//     },
//     {
//         id:16,
//         pfp: icon_employee_profile,
//         emp_id:" "88",
//         emp_name: "Emma Watson",
//         emp_mail: "Emma@piktorlabs.com",
//         emp_role: "Product Manager",
//         emp_mob: "9876543210",
//         emp_date: "Jan 1, 2020", emp_manager:"",
//     },
//     {
//         id:17,
//         pfp: icon_employee_profile,
//         emp_id:" "87",
//         emp_name: "Rebecca James",
//         emp_mail: "Rebeccajames@piktorlabs.com",
//         emp_role: "Interaction Designer",
//         emp_mob: "9876543210",
//         emp_date: "Jan 1, 2020", emp_manager:"",
//     },
//     {
//         id:18,
//         pfp: icon_employee_profile,
//         emp_id:" "86",
//         emp_name: "Tania Rai",
//         emp_mail: "Tania@piktorlabs.com",
//         emp_role: "Data Analyst",
//         emp_mob: "9876543210",
//         emp_date: "Jan 1, 2020", emp_manager:"",
//     },
//     {
//         id:19,
//         pfp: icon_employee_profile,
//         emp_id:" "85",
//         emp_name: "Thomas Green",
//         emp_mail: "Thomasgreen@piktorlabs.com",
//         emp_role: "Software Engineer",
//         emp_mob: "9876543210",
//         emp_date: "Jan 1, 2020", emp_manager:"",
//     },
//     {
//         id:20,
//         pfp: icon_employee_profile,
//         emp_id:" "84",
//         emp_name: "Emily Clarke",
//         emp_mail: "Emily clarke@piktorlabs.com",
//         emp_role: "Web Developer",
//         emp_mob: "9876543210",
//         emp_date: "Jan 1, 2020", emp_manager:"",
//     },
//     {
//         id:21,
//         pfp: icon_employee_profile,
//         emp_id:" "83",
//         emp_name: "Summer Simpson",
//         emp_mail: "Summersimpsons@piktorlabs.com",
//         emp_role: "Web Developer",
//         emp_mob: "9876543210",
//         emp_date: "Jan 1, 2020", emp_manager:"",
//     },
//     {
//         id:22,
//         pfp: icon_employee_profile,
//         emp_id:" "82",
//         emp_name: "James White",
//         emp_mail: "James.w@piktorlabs.com",
//         emp_role: "Web Developer",
//         emp_mob: "9876543210",
//         emp_date: "Jan 1, 2020", emp_manager:"",
//     },
//     {
//         id:23,
//         pfp: icon_employee_profile,
//         emp_id:" "81",
//         emp_name: "Bernardo Galavis",
//         emp_mail: "bernardo.g@piktorlabs.com",
//         emp_role: "Web Developer",
//         emp_mob: "9876543210",
//         emp_date: "Jan 1, 2020", emp_manager:"",
//     },
//     {
//         id:24,
//         pfp: icon_employee_profile,
//         emp_id:" "80",
//         emp_name: "Ruby Pen",
//         emp_mail: "Ruby.p@piktorlabs.com",
//         emp_role: "Front End Developer",
//         emp_mob: "9876543210",
//         emp_date: "Jan 1, 2020", emp_manager:"",
//     },
//     {
//         id:25,
//         pfp: icon_employee_profile,
//         emp_id:" "79",
//         emp_name: "Theon Grey",
//         emp_mail: "Grey.theon@piktorlabs.com",
//         emp_role: "UX Designer",
//         emp_mob: "9876543210",
//         emp_date: "Jan 1, 2020", emp_manager:"",
//     },
//     {
//         id:26,
//         pfp: icon_employee_profile,
//         emp_id:" "78",
//         emp_name: "Ariana Grande",
//         emp_mail: "Ariana.g@piktorlabs.com",
//         emp_role: "Data Scientist",
//         emp_mob: "9876543210",
//         emp_date: "Jan 1, 2020", emp_manager:"",
//     },
//     {
//         id:27,
//         pfp: icon_employee_profile,
//         emp_id:" "77",
//         emp_name: "Emma Watson",
//         emp_mail: "Emma@piktorlabs.com",
//         emp_role: "Product Manager",
//         emp_mob: "9876543210",
//         emp_date: "Jan 1, 2020", emp_manager:"",
//     },
//     {
//         id:28,
//         pfp: icon_employee_profile,
//         emp_id:" "76",
//         emp_name: "Rebecca James",
//         emp_mail: "Rebeccajames@piktorlabs.com",
//         emp_role: "Interaction Designer",
//         emp_mob: "9876543210",
//         emp_date: "Jan 1, 2020", emp_manager:"",
//     },
//     {
//         id:29,
//         pfp: icon_employee_profile,
//         emp_id:" "75",
//         emp_name: "Tania Rai",
//         emp_mail: "Tania@piktorlabs.com",
//         emp_role: "Data Analyst",
//         emp_mob: "9876543210",
//         emp_date: "Jan 1, 2020", emp_manager:"",
//     },
//     {
//         id:30,
//         pfp: icon_employee_profile,
//         emp_id:" "74",
//         emp_name: "Thomas Green",
//         emp_mail: "Thomasgreen@piktorlabs.com",
//         emp_role: "Software Engineer",
//         emp_mob: "9876543210",
//         emp_date: "Jan 1, 2020", emp_manager:"",
//     },
//     {
//         id:31,
//         pfp: icon_employee_profile,
//         emp_id:" "73",
//         emp_name: "Emily Clarke",
//         emp_mail: "Emily clarke@piktorlabs.com",
//         emp_role: "Web Developer",
//         emp_mob: "9876543210",
//         emp_date: "Jan 1, 2020", emp_manager:"",
//     },
//     {
//         id:32,
//         pfp: icon_employee_profile,
//         emp_id:" "72",
//         emp_name: "Summer Simpson",
//         emp_mail: "Summersimpsons@piktorlabs.com",
//         emp_role: "Web Developer",
//         emp_mob: "9876543210",
//         emp_date: "Jan 1, 2020", emp_manager:"",
//     },
//     {
//         id:33,
//         pfp: icon_employee_profile,
//         emp_id:" "71",
//         emp_name: "James White",
//         emp_mail: "James.w@piktorlabs.com",
//         emp_role: "Web Developer",
//         emp_mob: "9876543210",
//         emp_date: "Jan 1, 2020", emp_manager:"",
//     },
//     {
//         id:34,
//         pfp: icon_employee_profile,
//         emp_id:" "70",
//         emp_name: "Bernardo Galavis",
//         emp_mail: "bernardo.g@piktorlabs.com",
//         emp_role: "Web Developer",
//         emp_mob: "9876543210",
//         emp_date: "Jan 1, 2020", emp_manager:"",
//     },
//     {
//         id:35,
//         pfp: icon_employee_profile,
//         emp_id:" "69",
//         emp_name: "Ruby Pen",
//         emp_mail: "Ruby.p@piktorlabs.com",
//         emp_role: "Front End Developer",
//         emp_mob: "9876543210",
//         emp_date: "Jan 1, 2020", emp_manager:"",
//     },
//     {
//         id:36,
//         pfp: icon_employee_profile,
//         emp_id:" "68",
//         emp_name: "Theon Grey",
//         emp_mail: "Grey.theon@piktorlabs.com",
//         emp_role: "UX Designer",
//         emp_mob: "9876543210",
//         emp_date: "Jan 1, 2020", emp_manager:"",
//     },
//     {
//         id:37,
//         pfp: icon_employee_profile,
//         emp_id:" "67",
//         emp_name: "Ariana Grande",
//         emp_mail: "Ariana.g@piktorlabs.com",
//         emp_role: "Data Scientist",
//         emp_mob: "9876543210",
//         emp_date: "Jan 1, 2020", emp_manager:"",
//     },
//     {
//         id:38,
//         pfp: icon_employee_profile,
//         emp_id:" "66",
//         emp_name: "Emma Watson",
//         emp_mail: "Emma@piktorlabs.com",
//         emp_role: "Product Manager",
//         emp_mob: "9876543210",
//         emp_date: "Jan 1, 2020", emp_manager:"",
//     },
//     {
//         id:39,
//         pfp: icon_employee_profile,
//         emp_id:" "65",
//         emp_name: "Rebecca James",
//         emp_mail: "Rebeccajames@piktorlabs.com",
//         emp_role: "Interaction Designer",
//         emp_mob: "9876543210",
//         emp_date: "Jan 1, 2020", emp_manager:"",
//     },
//     {
//         id:40,
//         pfp: icon_employee_profile,
//         emp_id:" "64",
//         emp_name: "Tania Rai",
//         emp_mail: "Tania@piktorlabs.com",
//         emp_role: "Data Analyst",
//         emp_mob: "9876543210",
//         emp_date: "Jan 1, 2020", emp_manager:"",
//     },
//     {
//         id:41,
//         pfp: icon_employee_profile,
//         emp_id:" "63",
//         emp_name: "Thomas Green",
//         emp_mail: "Thomasgreen@piktorlabs.com",
//         emp_role: "Software Engineer",
//         emp_mob: "9876543210",
//         emp_date: "Jan 1, 2020", emp_manager:"",
//     },
//     {
//         id:42,
//         pfp: icon_employee_profile,
//         emp_id:" "62",
//         emp_name: "Emily Clarke",
//         emp_mail: "Emily clarke@piktorlabs.com",
//         emp_role: "Web Developer",
//         emp_mob: "9876543210",
//         emp_date: "Jan 1, 2020", emp_manager:"",
//     },
//     {
//         id:43,
//         pfp: icon_employee_profile,
//         emp_id:" "61",
//         emp_name: "Summer Simpson",
//         emp_mail: "Summersimpsons@piktorlabs.com",
//         emp_role: "Web Developer",
//         emp_mob: "9876543210",
//         emp_date: "Jan 1, 2020", emp_manager:"",
//     },
//     {
//         id:44,
//         pfp: icon_employee_profile,
//         emp_id:" "60",
//         emp_name: "James White",
//         emp_mail: "James.w@piktorlabs.com",
//         emp_role: "Web Developer",
//         emp_mob: "9876543210",
//         emp_date: "Jan 1, 2020", emp_manager:"",
//     },
//     {
//         id:45,
//         pfp: icon_employee_profile,
//         emp_id:" "59",
//         emp_name: "Bernardo Galavis",
//         emp_mail: "bernardo.g@piktorlabs.com",
//         emp_role: "Web Developer",
//         emp_mob: "9876543210",
//         emp_date: "Jan 1, 2020", emp_manager:"",
//     },
//     {
//         id:46,
//         pfp: icon_employee_profile,
//         emp_id:" "58",
//         emp_name: "Ruby Pen",
//         emp_mail: "Ruby.p@piktorlabs.com",
//         emp_role: "Front End Developer",
//         emp_mob: "9876543210",
//         emp_date: "Jan 1, 2020", emp_manager:"",
//     },
//     {
//         id:47,
//         pfp: icon_employee_profile,
//         emp_id:" "57",
//         emp_name: "Theon Grey",
//         emp_mail: "Grey.theon@piktorlabs.com",
//         emp_role: "UX Designer",
//         emp_mob: "9876543210",
//         emp_date: "Jan 1, 2020", emp_manager:"",
//     },
//     {
//         id:48,
//         pfp: icon_employee_profile,
//         emp_id:" "56",
//         emp_name: "Ariana Grande",
//         emp_mail: "Ariana.g@piktorlabs.com",
//         emp_role: "Data Scientist",
//         emp_mob: "9876543210",
//         emp_date: "Jan 1, 2020", emp_manager:"",
//     },
//     {
//         id:49,
//         pfp: icon_employee_profile,
//         emp_id:" "55",
//         emp_name: "Emma Watson",
//         emp_mail: "Emma@piktorlabs.com",
//         emp_role: "Product Manager",
//         emp_mob: "9876543210",
//         emp_date: "Jan 1, 2020", emp_manager:"",
//     },
//     {
//         id:50,
//         pfp: icon_employee_profile,
//         emp_id:" "54",
//         emp_name: "Rebecca James",
//         emp_mail: "Rebeccajames@piktorlabs.com",
//         emp_role: "Interaction Designer",
//         emp_mob: "9876543210",
//         emp_date: "Jan 1, 2020", emp_manager:"",
//     },
//     {
//         id:51,
//         pfp: icon_employee_profile,
//         emp_id:" "53",
//         emp_name: "Tania Rai",
//         emp_mail: "Tania@piktorlabs.com",
//         emp_role: "Data Analyst",
//         emp_mob: "9876543210",
//         emp_date: "Jan 1, 2020", emp_manager:"",
//     },
//     {
//         id:52,
//         pfp: icon_employee_profile,
//         emp_id:" "52",
//         emp_name: "Thomas Green",
//         emp_mail: "Thomasgreen@piktorlabs.com",
//         emp_role: "Software Engineer",
//         emp_mob: "9876543210",
//         emp_date: "Jan 1, 2020", emp_manager:"",
//     },
//     {
//         id:53,
//         pfp: icon_employee_profile,
//         emp_id:" "51",
//         emp_name: "Emily Clarke",
//         emp_mail: "Emily clarke@piktorlabs.com",
//         emp_role: "Web Developer",
//         emp_mob: "9876543210",
//         emp_date: "Jan 1, 2020", emp_manager:"",
//     },
//     {
//         id:54,
//         pfp: icon_employee_profile,
//         emp_id:" "50",
//         emp_name: "Summer Simpson",
//         emp_mail: "Summersimpsons@piktorlabs.com",
//         emp_role: "Web Developer",
//         emp_mob: "9876543210",
//         emp_date: "Jan 1, 2020", emp_manager:"",
//     },
//     {
//         id:55,
//         pfp: icon_employee_profile,
//         emp_id:" "49",
//         emp_name: "James White",
//         emp_mail: "James.w@piktorlabs.com",
//         emp_role: "Web Developer",
//         emp_mob: "9876543210",
//         emp_date: "Jan 1, 2020", emp_manager:"",
//     },

// ];
[{id:1,pfp:icon_employee_profile,emp_id:"13",emp_name:"Daron Stummeyer",emp_mail:"dstummeyer0@scientificamerican.com",emp_role:"Subcontractor",emp_mob:"6207553187",emp_date:"Jan 1, 2020", emp_manager:""},
{id:2,pfp:icon_employee_profile,emp_id:"111",emp_name:"Cyril Pywell",emp_mail:"cpywell1@ask.com",emp_role:"Subcontractor",emp_mob:"5732668772",emp_date:"Jan 1, 2020", emp_manager:""},
{id:3,pfp:icon_employee_profile,emp_id:"181",emp_name:"Inigo Seatter",emp_mail:"iseatter2@plala.or.jp",emp_role:"Architect",emp_mob:"1548184640",emp_date:"Jan 1, 2020", emp_manager:""},
{id:4,pfp:icon_employee_profile,emp_id:"115",emp_name:"Ferdinande Renyard",emp_mail:"frenyard3@rambler.ru",emp_role:"Surveyor",emp_mob:"7628759106",emp_date:"Jan 1, 2020", emp_manager:""},
{id:5,pfp:icon_employee_profile,emp_id:"183",emp_name:"Ollie Gascard",emp_mail:"ogascard4@wordpress.org",emp_role:"Subcontractor",emp_mob:"1078237212",emp_date:"Jan 1, 2020", emp_manager:""},
{id:6,pfp:icon_employee_profile,emp_id:"176",emp_name:"Marin Hamstead",emp_mail:"mhamstead5@mozilla.org",emp_role:"Architect",emp_mob:"5266193352",emp_date:"Jan 1, 2020", emp_manager:""},
{id:7,pfp:icon_employee_profile,emp_id:"25",emp_name:"Jake Gilbey",emp_mail:"jgilbey6@deliciousdays.com",emp_role:"Construction Foreman",emp_mob:"5890477536",emp_date:"Jan 1, 2020", emp_manager:""},
{id:8,pfp:icon_employee_profile,emp_id:"270",emp_name:"Isobel Presdie",emp_mail:"ipresdie7@people.com.cn",emp_role:"Construction Foreman",emp_mob:"4265275060",emp_date:"Jan 1, 2020", emp_manager:""},
{id:9,pfp:icon_employee_profile,emp_id:"248",emp_name:"Shelby Smallcomb",emp_mail:"ssmallcomb8@github.com",emp_role:"Project Manager",emp_mob:"3940537403",emp_date:"Jan 1, 2020", emp_manager:""},
{id:10,pfp:icon_employee_profile,emp_id:"53",emp_name:"Conni Paszek",emp_mail:"cpaszek9@unc.edu",emp_role:"Engineer",emp_mob:"5723197673",emp_date:"Jan 1, 2020", emp_manager:""},
{id:11,pfp:icon_employee_profile,emp_id:"226",emp_name:"Krissy Clancy",emp_mail:"kclancya@cnet.com",emp_role:"Surveyor",emp_mob:"5915077412",emp_date:"Jan 1, 2020", emp_manager:""},
{id:12,pfp:icon_employee_profile,emp_id:"12",emp_name:"Ingaborg Dekeyser",emp_mail:"idekeyserb@jugem.jp",emp_role:"Project Manager",emp_mob:"1771021438",emp_date:"Jan 1, 2020", emp_manager:""},
{id:13,pfp:icon_employee_profile,emp_id:"69",emp_name:"Jammal Nibley",emp_mail:"jnibleyc@imgur.com",emp_role:"Engineer",emp_mob:"0733116043",emp_date:"Jan 1, 2020", emp_manager:""},
{id:14,pfp:icon_employee_profile,emp_id:"216",emp_name:"Quill Bartolomucci",emp_mail:"qbartolomuccid@tripod.com",emp_role:"Construction Expeditor",emp_mob:"5214802978",emp_date:"Jan 1, 2020", emp_manager:""},
{id:15,pfp:icon_employee_profile,emp_id:"138",emp_name:"Burke Karpets",emp_mail:"bkarpetse@opensource.org",emp_role:"Engineer",emp_mob:"6337105737",emp_date:"Jan 1, 2020", emp_manager:""},
{id:16,pfp:icon_employee_profile,emp_id:"106",emp_name:"Kaycee Jesse",emp_mail:"kjessef@multiply.com",emp_role:"Estimator",emp_mob:"4969795533",emp_date:"Jan 1, 2020", emp_manager:""},
{id:17,pfp:icon_employee_profile,emp_id:"96",emp_name:"Giacopo Farrey",emp_mail:"gfarreyg@vimeo.com",emp_role:"Supervisor",emp_mob:"9691578212",emp_date:"Jan 1, 2020", emp_manager:""},
{id:18,pfp:icon_employee_profile,emp_id:"259",emp_name:"Brigit Writer",emp_mail:"bwriterh@cdbaby.com",emp_role:"Subcontractor",emp_mob:"0819430722",emp_date:"Jan 1, 2020", emp_manager:""},
{id:19,pfp:icon_employee_profile,emp_id:"41",emp_name:"Faye Forton",emp_mail:"ffortoni@theguardian.com",emp_role:"Construction Manager",emp_mob:"3865791840",emp_date:"Jan 1, 2020", emp_manager:""},
{id:20,pfp:icon_employee_profile,emp_id:"257",emp_name:"Fielding Washbrook",emp_mail:"fwashbrookj@vkontakte.ru",emp_role:"Electrician",emp_mob:"9158132554",emp_date:"Jan 1, 2020", emp_manager:""},
{id:21,pfp:icon_employee_profile,emp_id:"247",emp_name:"Pandora Romagnosi",emp_mail:"promagnosik@uol.com.br",emp_role:"Construction Foreman",emp_mob:"7528230316",emp_date:"Jan 1, 2020", emp_manager:""},
{id:22,pfp:icon_employee_profile,emp_id:"118",emp_name:"Jillana Mandres",emp_mail:"jmandresl@epa.gov",emp_role:"Project Manager",emp_mob:"3109436434",emp_date:"Jan 1, 2020", emp_manager:""},
{id:23,pfp:icon_employee_profile,emp_id:"227",emp_name:"Gard Daniello",emp_mail:"gdaniellom@irs.gov",emp_role:"Surveyor",emp_mob:"0138737657",emp_date:"Jan 1, 2020", emp_manager:""},
{id:24,pfp:icon_employee_profile,emp_id:"226",emp_name:"Amitie Sturrock",emp_mail:"asturrockn@furl.net",emp_role:"Supervisor",emp_mob:"8003401879",emp_date:"Jan 1, 2020", emp_manager:""},
{id:25,pfp:icon_employee_profile,emp_id:"214",emp_name:"Stepha Fortey",emp_mail:"sforteyo@nyu.edu",emp_role:"Electrician",emp_mob:"9393030987",emp_date:"Jan 1, 2020", emp_manager:""},
{id:26,pfp:icon_employee_profile,emp_id:"82",emp_name:"Peterus Spyby",emp_mail:"pspybyp@icio.us",emp_role:"Project Manager",emp_mob:"6079950316",emp_date:"Jan 1, 2020", emp_manager:""},
{id:27,pfp:icon_employee_profile,emp_id:"75",emp_name:"Angelika Portam",emp_mail:"aportamq@wp.com",emp_role:"Electrician",emp_mob:"0421014644",emp_date:"Jan 1, 2020", emp_manager:""},
{id:28,pfp:icon_employee_profile,emp_id:"209",emp_name:"Aretha Sturt",emp_mail:"asturtr@uol.com.br",emp_role:"Electrician",emp_mob:"9582387211",emp_date:"Jan 1, 2020", emp_manager:""},
{id:29,pfp:icon_employee_profile,emp_id:"88",emp_name:"Bethanne Buckoke",emp_mail:"bbuckokes@163.com",emp_role:"Construction Foreman",emp_mob:"6028279315",emp_date:"Jan 1, 2020", emp_manager:""},
{id:30,pfp:icon_employee_profile,emp_id:"86",emp_name:"Peggie Grewer",emp_mail:"pgrewert@vistaprint.com",emp_role:"Construction Foreman",emp_mob:"6367940685",emp_date:"Jan 1, 2020", emp_manager:""},
{id:31,pfp:icon_employee_profile,emp_id:"5",emp_name:"Janina Serrell",emp_mail:"jserrellu@dropbox.com",emp_role:"Construction Worker",emp_mob:"8232356693",emp_date:"Jan 1, 2020", emp_manager:""},
{id:32,pfp:icon_employee_profile,emp_id:"218",emp_name:"Elisabeth Thiolier",emp_mail:"ethiolierv@ehow.com",emp_role:"Construction Expeditor",emp_mob:"7301605269",emp_date:"Jan 1, 2020", emp_manager:""},
{id:33,pfp:icon_employee_profile,emp_id:"90",emp_name:"Callie Richardeau",emp_mail:"crichardeauw@jiathis.com",emp_role:"Construction Manager",emp_mob:"5481069113",emp_date:"Jan 1, 2020", emp_manager:""},
{id:34,pfp:icon_employee_profile,emp_id:"27",emp_name:"Guglielma Banes",emp_mail:"gbanesx@wunderground.com",emp_role:"Subcontractor",emp_mob:"2395761028",emp_date:"Jan 1, 2020", emp_manager:""},
{id:35,pfp:icon_employee_profile,emp_id:"199",emp_name:"Carlin Bentzen",emp_mail:"cbentzeny@army.mil",emp_role:"Supervisor",emp_mob:"8830404004",emp_date:"Jan 1, 2020", emp_manager:""},
{id:36,pfp:icon_employee_profile,emp_id:"272",emp_name:"Leonid Turmall",emp_mail:"lturmallz@usa.gov",emp_role:"Electrician",emp_mob:"4932237022",emp_date:"Jan 1, 2020", emp_manager:""},
{id:37,pfp:icon_employee_profile,emp_id:"299",emp_name:"Dimitry Guthrum",emp_mail:"dguthrum10@imdb.com",emp_role:"Estimator",emp_mob:"3441874617",emp_date:"Jan 1, 2020", emp_manager:""},
{id:38,pfp:icon_employee_profile,emp_id:"121",emp_name:"Gearard Wheater",emp_mail:"gwheater11@reverbnation.com",emp_role:"Construction Manager",emp_mob:"3935977786",emp_date:"Jan 1, 2020", emp_manager:""},
{id:39,pfp:icon_employee_profile,emp_id:"56",emp_name:"Kira Serrurier",emp_mail:"kserrurier12@alexa.com",emp_role:"Construction Foreman",emp_mob:"8452014511",emp_date:"Jan 1, 2020", emp_manager:""},
{id:40,pfp:icon_employee_profile,emp_id:"59",emp_name:"Garwood Sheavills",emp_mail:"gsheavills13@quantcast.com",emp_role:"Supervisor",emp_mob:"7872272431",emp_date:"Jan 1, 2020", emp_manager:""},
{id:41,pfp:icon_employee_profile,emp_id:"114",emp_name:"Saudra Shalloo",emp_mail:"sshalloo14@nps.gov",emp_role:"Construction Worker",emp_mob:"4369905095",emp_date:"Jan 1, 2020", emp_manager:""},
{id:42,pfp:icon_employee_profile,emp_id:"85",emp_name:"Jake Farland",emp_mail:"jfarland15@indiegogo.com",emp_role:"Construction Expeditor",emp_mob:"5037953472",emp_date:"Jan 1, 2020", emp_manager:""},
{id:43,pfp:icon_employee_profile,emp_id:"153",emp_name:"Daveen Reignould",emp_mail:"dreignould16@clickbank.net",emp_role:"Construction Manager",emp_mob:"6657835361",emp_date:"Jan 1, 2020", emp_manager:""},
{id:44,pfp:icon_employee_profile,emp_id:"18",emp_name:"Corrina Stolting",emp_mail:"cstolting17@bluehost.com",emp_role:"Construction Manager",emp_mob:"3180868635",emp_date:"Jan 1, 2020", emp_manager:""},
{id:45,pfp:icon_employee_profile,emp_id:"227",emp_name:"Aveline Insole",emp_mail:"ainsole18@illinois.edu",emp_role:"Electrician",emp_mob:"9661533547",emp_date:"Jan 1, 2020", emp_manager:""},
{id:46,pfp:icon_employee_profile,emp_id:"156",emp_name:"Edithe Loukes",emp_mail:"eloukes19@pagesperso-orange.fr",emp_role:"Construction Foreman",emp_mob:"1089624298",emp_date:"Jan 1, 2020", emp_manager:""},
{id:47,pfp:icon_employee_profile,emp_id:"207",emp_name:"Gerhardine Winborn",emp_mail:"gwinborn1a@live.com",emp_role:"Construction Foreman",emp_mob:"0710766661",emp_date:"Jan 1, 2020", emp_manager:""},
{id:48,pfp:icon_employee_profile,emp_id:"115",emp_name:"Rowney McCrostie",emp_mail:"rmccrostie1b@constantcontact.com",emp_role:"Electrician",emp_mob:"7321320782",emp_date:"Jan 1, 2020", emp_manager:""},
{id:49,pfp:icon_employee_profile,emp_id:"290",emp_name:"Dodie Bullers",emp_mail:"dbullers1c@gizmodo.com",emp_role:"Subcontractor",emp_mob:"8984789283",emp_date:"Jan 1, 2020", emp_manager:""},
{id:50,pfp:icon_employee_profile,emp_id:"195",emp_name:"Kelcy Renol",emp_mail:"krenol1d@nps.gov",emp_role:"Project Manager",emp_mob:"9331000642",emp_date:"Jan 1, 2020", emp_manager:""},
{id:51,pfp:icon_employee_profile,emp_id:"253",emp_name:"Netta McRobb",emp_mail:"nmcrobb1e@jiathis.com",emp_role:"Project Manager",emp_mob:"4154380222",emp_date:"Jan 1, 2020", emp_manager:""},
{id:52,pfp:icon_employee_profile,emp_id:"14",emp_name:"Pasquale O'Hannen",emp_mail:"pohannen1f@wikipedia.org",emp_role:"Supervisor",emp_mob:"1730697607",emp_date:"Jan 1, 2020", emp_manager:""},
{id:53,pfp:icon_employee_profile,emp_id:"36",emp_name:"Hyatt Fulford",emp_mail:"hfulford1g@hexun.com",emp_role:"Construction Foreman",emp_mob:"8829030732",emp_date:"Jan 1, 2020", emp_manager:""},
{id:54,pfp:icon_employee_profile,emp_id:"180",emp_name:"Tad Schowenburg",emp_mail:"tschowenburg1h@rakuten.co.jp",emp_role:"Architect",emp_mob:"2777265585",emp_date:"Jan 1, 2020", emp_manager:""},
{id:55,pfp:icon_employee_profile,emp_id:"161",emp_name:"Freddie Dyerson",emp_mail:"fdyerson1i@rakuten.co.jp",emp_role:"Construction Manager",emp_mob:"6249908838",emp_date:"Jan 1, 2020", emp_manager:""},
{id:56,pfp:icon_employee_profile,emp_id:"243",emp_name:"Krispin Rubertis",emp_mail:"krubertis1j@clickbank.net",emp_role:"Subcontractor",emp_mob:"7045678134",emp_date:"Jan 1, 2020", emp_manager:""},
{id:57,pfp:icon_employee_profile,emp_id:"71",emp_name:"Bettine Treves",emp_mail:"btreves1k@zimbio.com",emp_role:"Construction Worker",emp_mob:"8157002931",emp_date:"Jan 1, 2020", emp_manager:""},
{id:58,pfp:icon_employee_profile,emp_id:"83",emp_name:"Rena Feak",emp_mail:"rfeak1l@eventbrite.com",emp_role:"Subcontractor",emp_mob:"5749919226",emp_date:"Jan 1, 2020", emp_manager:""},
{id:59,pfp:icon_employee_profile,emp_id:"292",emp_name:"Rutger Latchmore",emp_mail:"rlatchmore1m@telegraph.co.uk",emp_role:"Project Manager",emp_mob:"8223156377",emp_date:"Jan 1, 2020", emp_manager:""},
{id:60,pfp:icon_employee_profile,emp_id:"274",emp_name:"Bern Staniford",emp_mail:"bstaniford1n@bbc.co.uk",emp_role:"Estimator",emp_mob:"1402032498",emp_date:"Jan 1, 2020", emp_manager:""},
{id:61,pfp:icon_employee_profile,emp_id:"35",emp_name:"Johny Bompass",emp_mail:"jbompass1o@360.cn",emp_role:"Construction Worker",emp_mob:"0323700373",emp_date:"Jan 1, 2020", emp_manager:""},
{id:62,pfp:icon_employee_profile,emp_id:"76",emp_name:"Jerrylee Shalders",emp_mail:"jshalders1p@miibeian.gov.cn",emp_role:"Construction Worker",emp_mob:"5363438399",emp_date:"Jan 1, 2020", emp_manager:""},
{id:63,pfp:icon_employee_profile,emp_id:"174",emp_name:"Harris Cazereau",emp_mail:"hcazereau1q@vistaprint.com",emp_role:"Engineer",emp_mob:"5696053068",emp_date:"Jan 1, 2020", emp_manager:""},
{id:64,pfp:icon_employee_profile,emp_id:"13",emp_name:"Giffy Reese",emp_mail:"greese1r@telegraph.co.uk",emp_role:"Construction Worker",emp_mob:"3276323494",emp_date:"Jan 1, 2020", emp_manager:""},
{id:65,pfp:icon_employee_profile,emp_id:"57",emp_name:"Oberon Meo",emp_mail:"omeo1s@ycombinator.com",emp_role:"Subcontractor",emp_mob:"4190980587",emp_date:"Jan 1, 2020", emp_manager:""},
{id:66,pfp:icon_employee_profile,emp_id:"256",emp_name:"Derril O'Canavan",emp_mail:"docanavan1t@slate.com",emp_role:"Construction Worker",emp_mob:"7870078786",emp_date:"Jan 1, 2020", emp_manager:""},
{id:67,pfp:icon_employee_profile,emp_id:"82",emp_name:"Robena Buist",emp_mail:"rbuist1u@privacy.gov.au",emp_role:"Electrician",emp_mob:"2088162607",emp_date:"Jan 1, 2020", emp_manager:""},
{id:68,pfp:icon_employee_profile,emp_id:"282",emp_name:"Roslyn Tison",emp_mail:"rtison1v@cbc.ca",emp_role:"Supervisor",emp_mob:"5682068653",emp_date:"Jan 1, 2020", emp_manager:""},
{id:69,pfp:icon_employee_profile,emp_id:"56",emp_name:"Jim Marchello",emp_mail:"jmarchello1w@meetup.com",emp_role:"Subcontractor",emp_mob:"2541899688",emp_date:"Jan 1, 2020", emp_manager:""},
{id:70,pfp:icon_employee_profile,emp_id:"165",emp_name:"Jerrie Bruyet",emp_mail:"jbruyet1x@mozilla.org",emp_role:"Construction Foreman",emp_mob:"3573058809",emp_date:"Jan 1, 2020", emp_manager:""},
{id:71,pfp:icon_employee_profile,emp_id:"142",emp_name:"Sigrid Lawes",emp_mail:"slawes1y@moonfruit.com",emp_role:"Surveyor",emp_mob:"0998892440",emp_date:"Jan 1, 2020", emp_manager:""},
{id:72,pfp:icon_employee_profile,emp_id:"184",emp_name:"Emily Bissiker",emp_mail:"ebissiker1z@multiply.com",emp_role:"Construction Worker",emp_mob:"0430324359",emp_date:"Jan 1, 2020", emp_manager:""},
{id:73,pfp:icon_employee_profile,emp_id:"113",emp_name:"Pen Edgeler",emp_mail:"pedgeler20@tamu.edu",emp_role:"Supervisor",emp_mob:"7907901553",emp_date:"Jan 1, 2020", emp_manager:""},
{id:74,pfp:icon_employee_profile,emp_id:"143",emp_name:"Weider Salling",emp_mail:"wsalling21@typepad.com",emp_role:"Construction Worker",emp_mob:"5286474578",emp_date:"Jan 1, 2020", emp_manager:""},
{id:75,pfp:icon_employee_profile,emp_id:"75",emp_name:"Gerhard D'Onise",emp_mail:"gdonise22@admin.ch",emp_role:"Construction Worker",emp_mob:"8284158795",emp_date:"Jan 1, 2020", emp_manager:""},
{id:76,pfp:icon_employee_profile,emp_id:"191",emp_name:"Rabi Kippax",emp_mail:"rkippax23@blinklist.com",emp_role:"Estimator",emp_mob:"1368581161",emp_date:"Jan 1, 2020", emp_manager:""},
{id:77,pfp:icon_employee_profile,emp_id:"140",emp_name:"Claudelle Glading",emp_mail:"cglading24@bluehost.com",emp_role:"Construction Manager",emp_mob:"0470740396",emp_date:"Jan 1, 2020", emp_manager:""},
{id:78,pfp:icon_employee_profile,emp_id:"187",emp_name:"Waite Oakey",emp_mail:"woakey25@gnu.org",emp_role:"Subcontractor",emp_mob:"5588358198",emp_date:"Jan 1, 2020", emp_manager:""},
{id:79,pfp:icon_employee_profile,emp_id:"124",emp_name:"Blake Hardie",emp_mail:"bhardie26@sciencedirect.com",emp_role:"Architect",emp_mob:"4071881232",emp_date:"Jan 1, 2020", emp_manager:""},
{id:80,pfp:icon_employee_profile,emp_id:"182",emp_name:"Gabriele Hallt",emp_mail:"ghallt27@businesswire.com",emp_role:"Surveyor",emp_mob:"2655457749",emp_date:"Jan 1, 2020", emp_manager:""},
{id:81,pfp:icon_employee_profile,emp_id:"76",emp_name:"Pearle Shwenn",emp_mail:"pshwenn28@jimdo.com",emp_role:"Estimator",emp_mob:"1277153213",emp_date:"Jan 1, 2020", emp_manager:""},
{id:82,pfp:icon_employee_profile,emp_id:"246",emp_name:"Wiatt Brimm",emp_mail:"wbrimm29@bravesites.com",emp_role:"Construction Manager",emp_mob:"6283356761",emp_date:"Jan 1, 2020", emp_manager:""},
{id:83,pfp:icon_employee_profile,emp_id:"86",emp_name:"Reeva Moan",emp_mail:"rmoan2a@soundcloud.com",emp_role:"Surveyor",emp_mob:"5758269085",emp_date:"Jan 1, 2020", emp_manager:""},
{id:84,pfp:icon_employee_profile,emp_id:"257",emp_name:"Percy Gilbert",emp_mail:"pgilbert2b@zimbio.com",emp_role:"Construction Worker",emp_mob:"0228085187",emp_date:"Jan 1, 2020", emp_manager:""},
{id:85,pfp:icon_employee_profile,emp_id:"3",emp_name:"Lilli Bamb",emp_mail:"lbamb2c@bizjournals.com",emp_role:"Supervisor",emp_mob:"2418635341",emp_date:"Jan 1, 2020", emp_manager:""},
{id:86,pfp:icon_employee_profile,emp_id:"120",emp_name:"Demetre Rainforth",emp_mail:"drainforth2d@twitpic.com",emp_role:"Engineer",emp_mob:"6123274767",emp_date:"Jan 1, 2020", emp_manager:""},
{id:87,pfp:icon_employee_profile,emp_id:"252",emp_name:"Eamon Grime",emp_mail:"egrime2e@surveymonkey.com",emp_role:"Construction Worker",emp_mob:"9759718308",emp_date:"Jan 1, 2020", emp_manager:""},
{id:88,pfp:icon_employee_profile,emp_id:"198",emp_name:"Rodrique Bikker",emp_mail:"rbikker2f@va.gov",emp_role:"Construction Worker",emp_mob:"7971072589",emp_date:"Jan 1, 2020", emp_manager:""},
{id:89,pfp:icon_employee_profile,emp_id:"16",emp_name:"Pansy Allenby",emp_mail:"pallenby2g@cisco.com",emp_role:"Construction Manager",emp_mob:"2578955603",emp_date:"Jan 1, 2020", emp_manager:""},
{id:90,pfp:icon_employee_profile,emp_id:"85",emp_name:"Skylar Vasilischev",emp_mail:"svasilischev2h@yolasite.com",emp_role:"Construction Worker",emp_mob:"5824846960",emp_date:"Jan 1, 2020", emp_manager:""},
{id:91,pfp:icon_employee_profile,emp_id:"254",emp_name:"Anthia Bunt",emp_mail:"abunt2i@msn.com",emp_role:"Subcontractor",emp_mob:"4834742725",emp_date:"Jan 1, 2020", emp_manager:""},
{id:92,pfp:icon_employee_profile,emp_id:"180",emp_name:"Millicent Goodhall",emp_mail:"mgoodhall2j@canalblog.com",emp_role:"Architect",emp_mob:"1481359290",emp_date:"Jan 1, 2020", emp_manager:""},
{id:93,pfp:icon_employee_profile,emp_id:"297",emp_name:"Kristofor Taylder",emp_mail:"ktaylder2k@yandex.ru",emp_role:"Supervisor",emp_mob:"2084512476",emp_date:"Jan 1, 2020", emp_manager:""},
{id:94,pfp:icon_employee_profile,emp_id:"119",emp_name:"Chas Galsworthy",emp_mail:"cgalsworthy2l@goodreads.com",emp_role:"Construction Worker",emp_mob:"8762625098",emp_date:"Jan 1, 2020", emp_manager:""},
{id:95,pfp:icon_employee_profile,emp_id:"44",emp_name:"Cornall Whiskerd",emp_mail:"cwhiskerd2m@ucoz.ru",emp_role:"Subcontractor",emp_mob:"4522063784",emp_date:"Jan 1, 2020", emp_manager:""},
{id:96,pfp:icon_employee_profile,emp_id:"90",emp_name:"Jervis Gourlie",emp_mail:"jgourlie2n@constantcontact.com",emp_role:"Supervisor",emp_mob:"7716699067",emp_date:"Jan 1, 2020", emp_manager:""},
{id:97,pfp:icon_employee_profile,emp_id:"252",emp_name:"Elsa Wayper",emp_mail:"ewayper2o@dyndns.org",emp_role:"Supervisor",emp_mob:"0971721467",emp_date:"Jan 1, 2020", emp_manager:""},
{id:98,pfp:icon_employee_profile,emp_id:"297",emp_name:"Kitty Krates",emp_mail:"kkrates2p@ed.gov",emp_role:"Supervisor",emp_mob:"6060502253",emp_date:"Jan 1, 2020", emp_manager:""},
{id:99,pfp:icon_employee_profile,emp_id:"21",emp_name:"Leann Marages",emp_mail:"lmarages2q@google.es",emp_role:"Surveyor",emp_mob:"0715163582",emp_date:"Jan 1, 2020", emp_manager:""},
{id:100,pfp:icon_employee_profile,emp_id:"34",emp_name:"Townie Ashburne",emp_mail:"tashburne2r@google.co.uk",emp_role:"Construction Manager",emp_mob:"0729125637",emp_date:"Jan 1, 2020", emp_manager:""},
{id:101,pfp:icon_employee_profile,emp_id:"144",emp_name:"Sandra Fosten",emp_mail:"sfosten2s@wired.com",emp_role:"Surveyor",emp_mob:"0853592365",emp_date:"Jan 1, 2020", emp_manager:""},
{id:102,pfp:icon_employee_profile,emp_id:"190",emp_name:"Rooney Winders",emp_mail:"rwinders2t@webmd.com",emp_role:"Estimator",emp_mob:"4040386086",emp_date:"Jan 1, 2020", emp_manager:""},
{id:103,pfp:icon_employee_profile,emp_id:"78",emp_name:"Mayne Hanbridge",emp_mail:"mhanbridge2u@omniture.com",emp_role:"Engineer",emp_mob:"4473768805",emp_date:"Jan 1, 2020", emp_manager:""},
{id:104,pfp:icon_employee_profile,emp_id:"154",emp_name:"Lizzy Rennebach",emp_mail:"lrennebach2v@abc.net.au",emp_role:"Construction Manager",emp_mob:"0576042935",emp_date:"Jan 1, 2020", emp_manager:""},
{id:105,pfp:icon_employee_profile,emp_id:"46",emp_name:"Donnajean Dunrige",emp_mail:"ddunrige2w@pinterest.com",emp_role:"Construction Foreman",emp_mob:"4087223604",emp_date:"Jan 1, 2020", emp_manager:""},
{id:106,pfp:icon_employee_profile,emp_id:"118",emp_name:"Zaccaria Skillern",emp_mail:"zskillern2x@qq.com",emp_role:"Construction Manager",emp_mob:"7910079400",emp_date:"Jan 1, 2020", emp_manager:""},
{id:107,pfp:icon_employee_profile,emp_id:"49",emp_name:"Nikoletta Crichley",emp_mail:"ncrichley2y@fda.gov",emp_role:"Electrician",emp_mob:"4126166475",emp_date:"Jan 1, 2020", emp_manager:""},
{id:108,pfp:icon_employee_profile,emp_id:"194",emp_name:"Wally Scourfield",emp_mail:"wscourfield2z@imgur.com",emp_role:"Construction Manager",emp_mob:"7480053312",emp_date:"Jan 1, 2020", emp_manager:""},
{id:109,pfp:icon_employee_profile,emp_id:"55",emp_name:"Norrie Von Hindenburg",emp_mail:"nvon30@fastcompany.com",emp_role:"Subcontractor",emp_mob:"7074781479",emp_date:"Jan 1, 2020", emp_manager:""},
{id:110,pfp:icon_employee_profile,emp_id:"29",emp_name:"Ernaline Hartnup",emp_mail:"ehartnup31@discovery.com",emp_role:"Construction Worker",emp_mob:"3572689120",emp_date:"Jan 1, 2020", emp_manager:""},
{id:111,pfp:icon_employee_profile,emp_id:"69",emp_name:"Wynn Noone",emp_mail:"wnoone32@prnewswire.com",emp_role:"Construction Foreman",emp_mob:"8590547736",emp_date:"Jan 1, 2020", emp_manager:""},
{id:112,pfp:icon_employee_profile,emp_id:"290",emp_name:"Kipp Piwall",emp_mail:"kpiwall33@tmall.com",emp_role:"Construction Worker",emp_mob:"1928914594",emp_date:"Jan 1, 2020", emp_manager:""},
{id:113,pfp:icon_employee_profile,emp_id:"133",emp_name:"Brant Grindall",emp_mail:"bgrindall34@digg.com",emp_role:"Surveyor",emp_mob:"6660373225",emp_date:"Jan 1, 2020", emp_manager:""},
{id:114,pfp:icon_employee_profile,emp_id:"124",emp_name:"Tanney Laimable",emp_mail:"tlaimable35@spotify.com",emp_role:"Surveyor",emp_mob:"8848337570",emp_date:"Jan 1, 2020", emp_manager:""},
{id:115,pfp:icon_employee_profile,emp_id:"258",emp_name:"Willey Tipling",emp_mail:"wtipling36@hp.com",emp_role:"Supervisor",emp_mob:"2507467711",emp_date:"Jan 1, 2020", emp_manager:""},
{id:116,pfp:icon_employee_profile,emp_id:"277",emp_name:"Penelope Magner",emp_mail:"pmagner37@123-reg.co.uk",emp_role:"Construction Foreman",emp_mob:"8274125266",emp_date:"Jan 1, 2020", emp_manager:""},
{id:117,pfp:icon_employee_profile,emp_id:"85",emp_name:"Clerc Hurford",emp_mail:"churford38@bloglines.com",emp_role:"Estimator",emp_mob:"3966281422",emp_date:"Jan 1, 2020", emp_manager:""},
{id:118,pfp:icon_employee_profile,emp_id:"109",emp_name:"Zolly Dillamore",emp_mail:"zdillamore39@yelp.com",emp_role:"Architect",emp_mob:"5207600672",emp_date:"Jan 1, 2020", emp_manager:""},
{id:119,pfp:icon_employee_profile,emp_id:"36",emp_name:"Cassy Westhoff",emp_mail:"cwesthoff3a@over-blog.com",emp_role:"Subcontractor",emp_mob:"3375397518",emp_date:"Jan 1, 2020", emp_manager:""},
{id:120,pfp:icon_employee_profile,emp_id:"20",emp_name:"Sancho Anstis",emp_mail:"sanstis3b@godaddy.com",emp_role:"Electrician",emp_mob:"3310885054",emp_date:"Jan 1, 2020", emp_manager:""},
{id:121,pfp:icon_employee_profile,emp_id:"17",emp_name:"Tina Varndell",emp_mail:"tvarndell3c@cpanel.net",emp_role:"Construction Expeditor",emp_mob:"6804854306",emp_date:"Jan 1, 2020", emp_manager:""},
{id:122,pfp:icon_employee_profile,emp_id:"145",emp_name:"Freddie Yoselevitch",emp_mail:"fyoselevitch3d@homestead.com",emp_role:"Estimator",emp_mob:"7088967871",emp_date:"Jan 1, 2020", emp_manager:""},
{id:123,pfp:icon_employee_profile,emp_id:"255",emp_name:"Jerome Wardhaugh",emp_mail:"jwardhaugh3e@theatlantic.com",emp_role:"Electrician",emp_mob:"2387049764",emp_date:"Jan 1, 2020", emp_manager:""},
{id:124,pfp:icon_employee_profile,emp_id:"192",emp_name:"Vasilis Ahrendsen",emp_mail:"vahrendsen3f@a8.net",emp_role:"Project Manager",emp_mob:"4383024688",emp_date:"Jan 1, 2020", emp_manager:""},
{id:125,pfp:icon_employee_profile,emp_id:"40",emp_name:"Edd Enrigo",emp_mail:"eenrigo3g@independent.co.uk",emp_role:"Construction Manager",emp_mob:"4073719386",emp_date:"Jan 1, 2020", emp_manager:""},
{id:126,pfp:icon_employee_profile,emp_id:"43",emp_name:"Saunder Varren",emp_mail:"svarren3h@chicagotribune.com",emp_role:"Electrician",emp_mob:"3038897140",emp_date:"Jan 1, 2020", emp_manager:""},
{id:127,pfp:icon_employee_profile,emp_id:"46",emp_name:"Temple Rockwill",emp_mail:"trockwill3i@nature.com",emp_role:"Estimator",emp_mob:"1711705454",emp_date:"Jan 1, 2020", emp_manager:""},
{id:128,pfp:icon_employee_profile,emp_id:"79",emp_name:"Leonelle Tiler",emp_mail:"ltiler3j@hexun.com",emp_role:"Supervisor",emp_mob:"4413666488",emp_date:"Jan 1, 2020", emp_manager:""},
{id:129,pfp:icon_employee_profile,emp_id:"76",emp_name:"Teador Ruos",emp_mail:"truos3k@senate.gov",emp_role:"Estimator",emp_mob:"3735457851",emp_date:"Jan 1, 2020", emp_manager:""},
{id:130,pfp:icon_employee_profile,emp_id:"267",emp_name:"Gena Ulyatt",emp_mail:"gulyatt3l@patch.com",emp_role:"Surveyor",emp_mob:"0799212938",emp_date:"Jan 1, 2020", emp_manager:""},
{id:131,pfp:icon_employee_profile,emp_id:"157",emp_name:"Rita Klambt",emp_mail:"rklambt3m@wikimedia.org",emp_role:"Construction Foreman",emp_mob:"0920808727",emp_date:"Jan 1, 2020", emp_manager:""},
{id:132,pfp:icon_employee_profile,emp_id:"257",emp_name:"Stevie Liveley",emp_mail:"sliveley3n@phpbb.com",emp_role:"Construction Worker",emp_mob:"9736578208",emp_date:"Jan 1, 2020", emp_manager:""},
{id:133,pfp:icon_employee_profile,emp_id:"263",emp_name:"Shalna Brodley",emp_mail:"sbrodley3o@theguardian.com",emp_role:"Estimator",emp_mob:"7967626109",emp_date:"Jan 1, 2020", emp_manager:""},
{id:134,pfp:icon_employee_profile,emp_id:"233",emp_name:"Zondra Rosell",emp_mail:"zrosell3p@typepad.com",emp_role:"Surveyor",emp_mob:"7563708162",emp_date:"Jan 1, 2020", emp_manager:""},
{id:135,pfp:icon_employee_profile,emp_id:"70",emp_name:"Mano McClosh",emp_mail:"mmcclosh3q@istockphoto.com",emp_role:"Supervisor",emp_mob:"8841121033",emp_date:"Jan 1, 2020", emp_manager:""},
{id:136,pfp:icon_employee_profile,emp_id:"277",emp_name:"Al Boam",emp_mail:"aboam3r@mapy.cz",emp_role:"Architect",emp_mob:"5873196486",emp_date:"Jan 1, 2020", emp_manager:""},
{id:137,pfp:icon_employee_profile,emp_id:"277",emp_name:"Barbette Pegler",emp_mail:"bpegler3s@bloglines.com",emp_role:"Supervisor",emp_mob:"3497515965",emp_date:"Jan 1, 2020", emp_manager:""},
{id:138,pfp:icon_employee_profile,emp_id:"232",emp_name:"Carlie Custy",emp_mail:"ccusty3t@friendfeed.com",emp_role:"Construction Manager",emp_mob:"6547590143",emp_date:"Jan 1, 2020", emp_manager:""},
{id:139,pfp:icon_employee_profile,emp_id:"63",emp_name:"Ibbie Aistrop",emp_mail:"iaistrop3u@hostgator.com",emp_role:"Construction Expeditor",emp_mob:"5249761119",emp_date:"Jan 1, 2020", emp_manager:""},
{id:140,pfp:icon_employee_profile,emp_id:"53",emp_name:"Ina Tuckley",emp_mail:"ituckley3v@scientificamerican.com",emp_role:"Supervisor",emp_mob:"1778536719",emp_date:"Jan 1, 2020", emp_manager:""},
{id:141,pfp:icon_employee_profile,emp_id:"153",emp_name:"Kin Stiffell",emp_mail:"kstiffell3w@home.pl",emp_role:"Electrician",emp_mob:"6560132684",emp_date:"Jan 1, 2020", emp_manager:""},
{id:142,pfp:icon_employee_profile,emp_id:"246",emp_name:"Woodman Duddan",emp_mail:"wduddan3x@sohu.com",emp_role:"Estimator",emp_mob:"1309623155",emp_date:"Jan 1, 2020", emp_manager:""},
{id:143,pfp:icon_employee_profile,emp_id:"126",emp_name:"Brendan Roggerone",emp_mail:"broggerone3y@spiegel.de",emp_role:"Supervisor",emp_mob:"0588022284",emp_date:"Jan 1, 2020", emp_manager:""},
{id:144,pfp:icon_employee_profile,emp_id:"40",emp_name:"Fonz Brodie",emp_mail:"fbrodie3z@cbc.ca",emp_role:"Construction Foreman",emp_mob:"2448220158",emp_date:"Jan 1, 2020", emp_manager:""},
{id:145,pfp:icon_employee_profile,emp_id:"296",emp_name:"Kylynn Barwis",emp_mail:"kbarwis40@auda.org.au",emp_role:"Construction Foreman",emp_mob:"3031181670",emp_date:"Jan 1, 2020", emp_manager:""},
{id:146,pfp:icon_employee_profile,emp_id:"156",emp_name:"Sophey Gilman",emp_mail:"sgilman41@symantec.com",emp_role:"Surveyor",emp_mob:"4711377808",emp_date:"Jan 1, 2020", emp_manager:""},
{id:147,pfp:icon_employee_profile,emp_id:"114",emp_name:"Cyndi Feeny",emp_mail:"cfeeny42@tinypic.com",emp_role:"Construction Foreman",emp_mob:"1527014398",emp_date:"Jan 1, 2020", emp_manager:""},
{id:148,pfp:icon_employee_profile,emp_id:"78",emp_name:"Colline Boyett",emp_mail:"cboyett43@nbcnews.com",emp_role:"Subcontractor",emp_mob:"3870248149",emp_date:"Jan 1, 2020", emp_manager:""},
{id:149,pfp:icon_employee_profile,emp_id:"149",emp_name:"Zitella Kier",emp_mail:"zkier44@google.co.uk",emp_role:"Construction Foreman",emp_mob:"5277710566",emp_date:"Jan 1, 2020", emp_manager:""},
{id:150,pfp:icon_employee_profile,emp_id:"152",emp_name:"Beverly Gullyes",emp_mail:"bgullyes45@dyndns.org",emp_role:"Engineer",emp_mob:"8030593473",emp_date:"Jan 1, 2020", emp_manager:""},
{id:151,pfp:icon_employee_profile,emp_id:"10",emp_name:"Nevin Linney",emp_mail:"nlinney46@wiley.com",emp_role:"Supervisor",emp_mob:"2290667544",emp_date:"Jan 1, 2020", emp_manager:""},
{id:152,pfp:icon_employee_profile,emp_id:"209",emp_name:"Jamison Mathiasen",emp_mail:"jmathiasen47@webeden.co.uk",emp_role:"Electrician",emp_mob:"6336667057",emp_date:"Jan 1, 2020", emp_manager:""},
{id:153,pfp:icon_employee_profile,emp_id:"39",emp_name:"Dane Privett",emp_mail:"dprivett48@usatoday.com",emp_role:"Construction Expeditor",emp_mob:"6673203471",emp_date:"Jan 1, 2020", emp_manager:""},
{id:154,pfp:icon_employee_profile,emp_id:"231",emp_name:"Adrianne Sherrett",emp_mail:"asherrett49@blog.com",emp_role:"Engineer",emp_mob:"6969615073",emp_date:"Jan 1, 2020", emp_manager:""},
{id:155,pfp:icon_employee_profile,emp_id:"207",emp_name:"Cayla Guion",emp_mail:"cguion4a@bravesites.com",emp_role:"Surveyor",emp_mob:"7247022523",emp_date:"Jan 1, 2020", emp_manager:""},
{id:156,pfp:icon_employee_profile,emp_id:"149",emp_name:"Graham Domney",emp_mail:"gdomney4b@youtu.be",emp_role:"Subcontractor",emp_mob:"1073962164",emp_date:"Jan 1, 2020", emp_manager:""},
{id:157,pfp:icon_employee_profile,emp_id:"135",emp_name:"Tab Skoyles",emp_mail:"tskoyles4c@mapy.cz",emp_role:"Architect",emp_mob:"7422544902",emp_date:"Jan 1, 2020", emp_manager:""},
{id:158,pfp:icon_employee_profile,emp_id:"38",emp_name:"Carlie Crangle",emp_mail:"ccrangle4d@comcast.net",emp_role:"Estimator",emp_mob:"6343912657",emp_date:"Jan 1, 2020", emp_manager:""},
{id:159,pfp:icon_employee_profile,emp_id:"9",emp_name:"Alvera Seton",emp_mail:"aseton4e@who.int",emp_role:"Project Manager",emp_mob:"6702162316",emp_date:"Jan 1, 2020", emp_manager:""},
{id:160,pfp:icon_employee_profile,emp_id:"298",emp_name:"Carmella Slyde",emp_mail:"cslyde4f@mtv.com",emp_role:"Engineer",emp_mob:"3592383981",emp_date:"Jan 1, 2020", emp_manager:""},
{id:161,pfp:icon_employee_profile,emp_id:"48",emp_name:"Stevana Schultes",emp_mail:"sschultes4g@imdb.com",emp_role:"Project Manager",emp_mob:"4966608368",emp_date:"Jan 1, 2020", emp_manager:""},
{id:162,pfp:icon_employee_profile,emp_id:"236",emp_name:"Brina Waskett",emp_mail:"bwaskett4h@wired.com",emp_role:"Construction Expeditor",emp_mob:"8333333508",emp_date:"Jan 1, 2020", emp_manager:""},
{id:163,pfp:icon_employee_profile,emp_id:"177",emp_name:"Min Roubert",emp_mail:"mroubert4i@google.nl",emp_role:"Supervisor",emp_mob:"2891367359",emp_date:"Jan 1, 2020", emp_manager:""},
{id:164,pfp:icon_employee_profile,emp_id:"70",emp_name:"Wilbert Jobes",emp_mail:"wjobes4j@guardian.co.uk",emp_role:"Architect",emp_mob:"5171891788",emp_date:"Jan 1, 2020", emp_manager:""},
{id:165,pfp:icon_employee_profile,emp_id:"236",emp_name:"Bram Kikke",emp_mail:"bkikke4k@issuu.com",emp_role:"Supervisor",emp_mob:"7714957905",emp_date:"Jan 1, 2020", emp_manager:""},
{id:166,pfp:icon_employee_profile,emp_id:"86",emp_name:"Garwood Tother",emp_mail:"gtother4l@vkontakte.ru",emp_role:"Estimator",emp_mob:"9295675142",emp_date:"Jan 1, 2020", emp_manager:""},
{id:167,pfp:icon_employee_profile,emp_id:"53",emp_name:"Benoite Flay",emp_mail:"bflay4m@google.pl",emp_role:"Electrician",emp_mob:"2202118039",emp_date:"Jan 1, 2020", emp_manager:""},
{id:168,pfp:icon_employee_profile,emp_id:"250",emp_name:"Joceline Sperwell",emp_mail:"jsperwell4n@ow.ly",emp_role:"Supervisor",emp_mob:"9110578811",emp_date:"Jan 1, 2020", emp_manager:""},
{id:169,pfp:icon_employee_profile,emp_id:"27",emp_name:"Katharyn Sturdgess",emp_mail:"ksturdgess4o@google.com.hk",emp_role:"Construction Worker",emp_mob:"3919105265",emp_date:"Jan 1, 2020", emp_manager:""},
{id:170,pfp:icon_employee_profile,emp_id:"33",emp_name:"Toni Broodes",emp_mail:"tbroodes4p@cbslocal.com",emp_role:"Supervisor",emp_mob:"3511867118",emp_date:"Jan 1, 2020", emp_manager:""},
{id:171,pfp:icon_employee_profile,emp_id:"23",emp_name:"Bibi Beecheno",emp_mail:"bbeecheno4q@nytimes.com",emp_role:"Construction Foreman",emp_mob:"7811568500",emp_date:"Jan 1, 2020", emp_manager:""},
{id:172,pfp:icon_employee_profile,emp_id:"120",emp_name:"Alexei Hendricks",emp_mail:"ahendricks4r@hc360.com",emp_role:"Construction Worker",emp_mob:"1154595137",emp_date:"Jan 1, 2020", emp_manager:""},
{id:173,pfp:icon_employee_profile,emp_id:"106",emp_name:"Brook Fisbey",emp_mail:"bfisbey4s@cloudflare.com",emp_role:"Construction Expeditor",emp_mob:"1813177724",emp_date:"Jan 1, 2020", emp_manager:""},
{id:174,pfp:icon_employee_profile,emp_id:"88",emp_name:"Alfreda Bolter",emp_mail:"abolter4t@uiuc.edu",emp_role:"Supervisor",emp_mob:"9797155323",emp_date:"Jan 1, 2020", emp_manager:""},
{id:175,pfp:icon_employee_profile,emp_id:"24",emp_name:"Gaspar Espadate",emp_mail:"gespadate4u@sogou.com",emp_role:"Construction Worker",emp_mob:"8163429402",emp_date:"Jan 1, 2020", emp_manager:""},
{id:176,pfp:icon_employee_profile,emp_id:"127",emp_name:"Thane Gare",emp_mail:"tgare4v@mac.com",emp_role:"Project Manager",emp_mob:"2373507706",emp_date:"Jan 1, 2020", emp_manager:""},
{id:177,pfp:icon_employee_profile,emp_id:"83",emp_name:"Skipper Hutfield",emp_mail:"shutfield4w@a8.net",emp_role:"Engineer",emp_mob:"7305600245",emp_date:"Jan 1, 2020", emp_manager:""},
{id:178,pfp:icon_employee_profile,emp_id:"105",emp_name:"Lek Fromont",emp_mail:"lfromont4x@springer.com",emp_role:"Estimator",emp_mob:"7116944257",emp_date:"Jan 1, 2020", emp_manager:""},
{id:179,pfp:icon_employee_profile,emp_id:"69",emp_name:"Aindrea Stranks",emp_mail:"astranks4y@vkontakte.ru",emp_role:"Estimator",emp_mob:"6663781650",emp_date:"Jan 1, 2020", emp_manager:""},
{id:180,pfp:icon_employee_profile,emp_id:"165",emp_name:"Marilin Duinbleton",emp_mail:"mduinbleton4z@cbc.ca",emp_role:"Construction Manager",emp_mob:"1750427362",emp_date:"Jan 1, 2020", emp_manager:""},
{id:181,pfp:icon_employee_profile,emp_id:"265",emp_name:"Kippar Belf",emp_mail:"kbelf50@mit.edu",emp_role:"Supervisor",emp_mob:"6340793703",emp_date:"Jan 1, 2020", emp_manager:""},
{id:182,pfp:icon_employee_profile,emp_id:"229",emp_name:"Pacorro Barnhart",emp_mail:"pbarnhart51@wiley.com",emp_role:"Surveyor",emp_mob:"5542221599",emp_date:"Jan 1, 2020", emp_manager:""},
{id:183,pfp:icon_employee_profile,emp_id:"154",emp_name:"Rozina Ducker",emp_mail:"rducker52@tamu.edu",emp_role:"Architect",emp_mob:"6046108837",emp_date:"Jan 1, 2020", emp_manager:""},
{id:184,pfp:icon_employee_profile,emp_id:"84",emp_name:"Myrvyn Ryding",emp_mail:"mryding53@ask.com",emp_role:"Estimator",emp_mob:"3321109239",emp_date:"Jan 1, 2020", emp_manager:""},
{id:185,pfp:icon_employee_profile,emp_id:"217",emp_name:"Chicky Branni",emp_mail:"cbranni54@liveinternet.ru",emp_role:"Electrician",emp_mob:"1705989950",emp_date:"Jan 1, 2020", emp_manager:""},
{id:186,pfp:icon_employee_profile,emp_id:"221",emp_name:"Noelyn Dockreay",emp_mail:"ndockreay55@washington.edu",emp_role:"Engineer",emp_mob:"4432059931",emp_date:"Jan 1, 2020", emp_manager:""},
{id:187,pfp:icon_employee_profile,emp_id:"234",emp_name:"Dorelia Belderfield",emp_mail:"dbelderfield56@livejournal.com",emp_role:"Construction Worker",emp_mob:"5304824849",emp_date:"Jan 1, 2020", emp_manager:""},
{id:188,pfp:icon_employee_profile,emp_id:"299",emp_name:"Chris Mundee",emp_mail:"cmundee57@archive.org",emp_role:"Construction Foreman",emp_mob:"4853336745",emp_date:"Jan 1, 2020", emp_manager:""},
{id:189,pfp:icon_employee_profile,emp_id:"112",emp_name:"Jory Hutcheon",emp_mail:"jhutcheon58@imdb.com",emp_role:"Project Manager",emp_mob:"3605811280",emp_date:"Jan 1, 2020", emp_manager:""},
{id:190,pfp:icon_employee_profile,emp_id:"64",emp_name:"Ludovico Cantillon",emp_mail:"lcantillon59@weather.com",emp_role:"Surveyor",emp_mob:"6764431140",emp_date:"Jan 1, 2020", emp_manager:""},
{id:191,pfp:icon_employee_profile,emp_id:"214",emp_name:"Anna-diana Hurdedge",emp_mail:"ahurdedge5a@europa.eu",emp_role:"Electrician",emp_mob:"7962514574",emp_date:"Jan 1, 2020", emp_manager:""},
{id:192,pfp:icon_employee_profile,emp_id:"269",emp_name:"Mac Lewens",emp_mail:"mlewens5b@furl.net",emp_role:"Construction Manager",emp_mob:"4288551242",emp_date:"Jan 1, 2020", emp_manager:""},
{id:193,pfp:icon_employee_profile,emp_id:"90",emp_name:"Beatrice Overnell",emp_mail:"bovernell5c@vimeo.com",emp_role:"Project Manager",emp_mob:"2441299662",emp_date:"Jan 1, 2020", emp_manager:""},
{id:194,pfp:icon_employee_profile,emp_id:"6",emp_name:"Hermie Bengal",emp_mail:"hbengal5d@woothemes.com",emp_role:"Surveyor",emp_mob:"9923670317",emp_date:"Jan 1, 2020", emp_manager:""},
{id:195,pfp:icon_employee_profile,emp_id:"45",emp_name:"Nicolai Bleackly",emp_mail:"nbleackly5e@google.co.uk",emp_role:"Engineer",emp_mob:"4397442916",emp_date:"Jan 1, 2020", emp_manager:""},
{id:196,pfp:icon_employee_profile,emp_id:"6",emp_name:"Avrit Lyddyard",emp_mail:"alyddyard5f@aboutads.info",emp_role:"Construction Worker",emp_mob:"6178215932",emp_date:"Jan 1, 2020", emp_manager:""},
{id:197,pfp:icon_employee_profile,emp_id:"225",emp_name:"Theodora Bees",emp_mail:"tbees5g@toplist.cz",emp_role:"Surveyor",emp_mob:"9846125372",emp_date:"Jan 1, 2020", emp_manager:""},
{id:198,pfp:icon_employee_profile,emp_id:"20",emp_name:"Giffard McIlmurray",emp_mail:"gmcilmurray5h@behance.net",emp_role:"Estimator",emp_mob:"9708757500",emp_date:"Jan 1, 2020", emp_manager:""},
{id:199,pfp:icon_employee_profile,emp_id:"271",emp_name:"Berty McNea",emp_mail:"bmcnea5i@msn.com",emp_role:"Construction Manager",emp_mob:"4530334821",emp_date:"Jan 1, 2020", emp_manager:""},
{id:200,pfp:icon_employee_profile,emp_id:"123",emp_name:"Rici Eagell",emp_mail:"reagell5j@wp.com",emp_role:"Construction Worker",emp_mob:"9951771718",emp_date:"Jan 1, 2020", emp_manager:""},
{id:201,pfp:icon_employee_profile,emp_id:"200",emp_name:"Eziechiele Hanretty",emp_mail:"ehanretty5k@cdc.gov",emp_role:"Electrician",emp_mob:"2798950228",emp_date:"Jan 1, 2020", emp_manager:""},
{id:202,pfp:icon_employee_profile,emp_id:"157",emp_name:"Briant Dabinett",emp_mail:"bdabinett5l@webs.com",emp_role:"Project Manager",emp_mob:"5428288817",emp_date:"Jan 1, 2020", emp_manager:""},
{id:203,pfp:icon_employee_profile,emp_id:"260",emp_name:"Tani Vedeneev",emp_mail:"tvedeneev5m@bravesites.com",emp_role:"Estimator",emp_mob:"0304540315",emp_date:"Jan 1, 2020", emp_manager:""},
{id:204,pfp:icon_employee_profile,emp_id:"199",emp_name:"Tiffie Faulconbridge",emp_mail:"tfaulconbridge5n@google.co.jp",emp_role:"Architect",emp_mob:"9395866284",emp_date:"Jan 1, 2020", emp_manager:""},
{id:205,pfp:icon_employee_profile,emp_id:"238",emp_name:"Sibylle Scroggie",emp_mail:"sscroggie5o@phpbb.com",emp_role:"Project Manager",emp_mob:"7107680080",emp_date:"Jan 1, 2020", emp_manager:""},
{id:206,pfp:icon_employee_profile,emp_id:"24",emp_name:"Martie Dumpleton",emp_mail:"mdumpleton5p@fc2.com",emp_role:"Construction Manager",emp_mob:"5258503852",emp_date:"Jan 1, 2020", emp_manager:""},
{id:207,pfp:icon_employee_profile,emp_id:"143",emp_name:"Manon Hatt",emp_mail:"mhatt5q@desdev.cn",emp_role:"Construction Expeditor",emp_mob:"8895254686",emp_date:"Jan 1, 2020", emp_manager:""},
{id:208,pfp:icon_employee_profile,emp_id:"23",emp_name:"Dari Bauduccio",emp_mail:"dbauduccio5r@shutterfly.com",emp_role:"Estimator",emp_mob:"6664430622",emp_date:"Jan 1, 2020", emp_manager:""},
{id:209,pfp:icon_employee_profile,emp_id:"164",emp_name:"Dorolice Habbon",emp_mail:"dhabbon5s@sohu.com",emp_role:"Architect",emp_mob:"0080036295",emp_date:"Jan 1, 2020", emp_manager:""},
{id:210,pfp:icon_employee_profile,emp_id:"52",emp_name:"Gaston Dugmore",emp_mail:"gdugmore5t@hatena.ne.jp",emp_role:"Engineer",emp_mob:"9937889774",emp_date:"Jan 1, 2020", emp_manager:""},
{id:211,pfp:icon_employee_profile,emp_id:"265",emp_name:"Blisse Heckney",emp_mail:"bheckney5u@hp.com",emp_role:"Surveyor",emp_mob:"8440460201",emp_date:"Jan 1, 2020", emp_manager:""},
{id:212,pfp:icon_employee_profile,emp_id:"167",emp_name:"Arlana Patley",emp_mail:"apatley5v@usnews.com",emp_role:"Estimator",emp_mob:"6394943789",emp_date:"Jan 1, 2020", emp_manager:""},
{id:213,pfp:icon_employee_profile,emp_id:"261",emp_name:"Vilhelmina Cellone",emp_mail:"vcellone5w@mac.com",emp_role:"Construction Manager",emp_mob:"5161634901",emp_date:"Jan 1, 2020", emp_manager:""},
{id:214,pfp:icon_employee_profile,emp_id:"201",emp_name:"Cornie Gregh",emp_mail:"cgregh5x@weibo.com",emp_role:"Construction Worker",emp_mob:"0931366860",emp_date:"Jan 1, 2020", emp_manager:""},
{id:215,pfp:icon_employee_profile,emp_id:"290",emp_name:"Lizzy Halloran",emp_mail:"lhalloran5y@mediafire.com",emp_role:"Construction Manager",emp_mob:"5652351411",emp_date:"Jan 1, 2020", emp_manager:""},
{id:216,pfp:icon_employee_profile,emp_id:"157",emp_name:"Fairleigh Brigham",emp_mail:"fbrigham5z@mtv.com",emp_role:"Construction Worker",emp_mob:"3720181545",emp_date:"Jan 1, 2020", emp_manager:""},
{id:217,pfp:icon_employee_profile,emp_id:"126",emp_name:"Mirabelle Delamar",emp_mail:"mdelamar60@cargocollective.com",emp_role:"Construction Foreman",emp_mob:"9105893720",emp_date:"Jan 1, 2020", emp_manager:""},
{id:218,pfp:icon_employee_profile,emp_id:"229",emp_name:"Parke Nickels",emp_mail:"pnickels61@msn.com",emp_role:"Engineer",emp_mob:"5795364894",emp_date:"Jan 1, 2020", emp_manager:""},
{id:219,pfp:icon_employee_profile,emp_id:"194",emp_name:"Gustie Bollis",emp_mail:"gbollis62@mysql.com",emp_role:"Architect",emp_mob:"0124630421",emp_date:"Jan 1, 2020", emp_manager:""},
{id:220,pfp:icon_employee_profile,emp_id:"78",emp_name:"Violante Paradis",emp_mail:"vparadis63@goodreads.com",emp_role:"Construction Foreman",emp_mob:"6447552428",emp_date:"Jan 1, 2020", emp_manager:""},
{id:221,pfp:icon_employee_profile,emp_id:"98",emp_name:"Madelyn Harnor",emp_mail:"mharnor64@deviantart.com",emp_role:"Construction Manager",emp_mob:"7797881472",emp_date:"Jan 1, 2020", emp_manager:""},
{id:222,pfp:icon_employee_profile,emp_id:"236",emp_name:"Krispin Thornborrow",emp_mail:"kthornborrow65@cyberchimps.com",emp_role:"Supervisor",emp_mob:"8936518631",emp_date:"Jan 1, 2020", emp_manager:""},
{id:223,pfp:icon_employee_profile,emp_id:"147",emp_name:"Garrott Meadus",emp_mail:"gmeadus66@xinhuanet.com",emp_role:"Architect",emp_mob:"9807812968",emp_date:"Jan 1, 2020", emp_manager:""},
{id:224,pfp:icon_employee_profile,emp_id:"37",emp_name:"Abramo Dighton",emp_mail:"adighton67@hexun.com",emp_role:"Engineer",emp_mob:"8570238436",emp_date:"Jan 1, 2020", emp_manager:""},
{id:225,pfp:icon_employee_profile,emp_id:"31",emp_name:"Nollie Sibbe",emp_mail:"nsibbe68@aboutads.info",emp_role:"Project Manager",emp_mob:"1433654962",emp_date:"Jan 1, 2020", emp_manager:""},
{id:226,pfp:icon_employee_profile,emp_id:"114",emp_name:"Vanna Catherick",emp_mail:"vcatherick69@businessinsider.com",emp_role:"Architect",emp_mob:"0408572612",emp_date:"Jan 1, 2020", emp_manager:""},
{id:227,pfp:icon_employee_profile,emp_id:"119",emp_name:"Gabriela Herion",emp_mail:"gherion6a@youku.com",emp_role:"Surveyor",emp_mob:"3913426140",emp_date:"Jan 1, 2020", emp_manager:""},
{id:228,pfp:icon_employee_profile,emp_id:"30",emp_name:"Vernice Bullers",emp_mail:"vbullers6b@economist.com",emp_role:"Project Manager",emp_mob:"1539388891",emp_date:"Jan 1, 2020", emp_manager:""},
{id:229,pfp:icon_employee_profile,emp_id:"167",emp_name:"Elsinore Rackley",emp_mail:"erackley6c@tamu.edu",emp_role:"Architect",emp_mob:"8141148923",emp_date:"Jan 1, 2020", emp_manager:""},
{id:230,pfp:icon_employee_profile,emp_id:"153",emp_name:"Brigit Spridgen",emp_mail:"bspridgen6d@theguardian.com",emp_role:"Surveyor",emp_mob:"7711176635",emp_date:"Jan 1, 2020", emp_manager:""},
{id:231,pfp:icon_employee_profile,emp_id:"172",emp_name:"Tami Pulford",emp_mail:"tpulford6e@unblog.fr",emp_role:"Estimator",emp_mob:"1112314075",emp_date:"Jan 1, 2020", emp_manager:""},
{id:232,pfp:icon_employee_profile,emp_id:"267",emp_name:"Ingra Bromige",emp_mail:"ibromige6f@csmonitor.com",emp_role:"Surveyor",emp_mob:"2435876343",emp_date:"Jan 1, 2020", emp_manager:""},
{id:233,pfp:icon_employee_profile,emp_id:"213",emp_name:"Waneta Bridgman",emp_mail:"wbridgman6g@meetup.com",emp_role:"Subcontractor",emp_mob:"1736583352",emp_date:"Jan 1, 2020", emp_manager:""},
{id:234,pfp:icon_employee_profile,emp_id:"295",emp_name:"Robinet Windous",emp_mail:"rwindous6h@reverbnation.com",emp_role:"Electrician",emp_mob:"2398573702",emp_date:"Jan 1, 2020", emp_manager:""},
{id:235,pfp:icon_employee_profile,emp_id:"192",emp_name:"Cybil Caughte",emp_mail:"ccaughte6i@cnbc.com",emp_role:"Supervisor",emp_mob:"6086115346",emp_date:"Jan 1, 2020", emp_manager:""},
{id:236,pfp:icon_employee_profile,emp_id:"111",emp_name:"Haily Baggally",emp_mail:"hbaggally6j@blog.com",emp_role:"Architect",emp_mob:"4534889372",emp_date:"Jan 1, 2020", emp_manager:""},
{id:237,pfp:icon_employee_profile,emp_id:"42",emp_name:"Patty Krugmann",emp_mail:"pkrugmann6k@over-blog.com",emp_role:"Supervisor",emp_mob:"3467406270",emp_date:"Jan 1, 2020", emp_manager:""},
{id:238,pfp:icon_employee_profile,emp_id:"181",emp_name:"Shena Sancias",emp_mail:"ssancias6l@odnoklassniki.ru",emp_role:"Construction Manager",emp_mob:"1009410938",emp_date:"Jan 1, 2020", emp_manager:""},
{id:239,pfp:icon_employee_profile,emp_id:"106",emp_name:"Brandise Gantzman",emp_mail:"bgantzman6m@dedecms.com",emp_role:"Electrician",emp_mob:"3580184229",emp_date:"Jan 1, 2020", emp_manager:""},
{id:240,pfp:icon_employee_profile,emp_id:"122",emp_name:"Ralf Vassel",emp_mail:"rvassel6n@nasa.gov",emp_role:"Surveyor",emp_mob:"8442722920",emp_date:"Jan 1, 2020", emp_manager:""},
{id:241,pfp:icon_employee_profile,emp_id:"209",emp_name:"Nollie Baggelley",emp_mail:"nbaggelley6o@a8.net",emp_role:"Architect",emp_mob:"3424471712",emp_date:"Jan 1, 2020", emp_manager:""},
{id:242,pfp:icon_employee_profile,emp_id:"29",emp_name:"Leah Bedder",emp_mail:"lbedder6p@state.gov",emp_role:"Estimator",emp_mob:"5717944381",emp_date:"Jan 1, 2020", emp_manager:""},
{id:243,pfp:icon_employee_profile,emp_id:"140",emp_name:"Bethina Spellessy",emp_mail:"bspellessy6q@accuweather.com",emp_role:"Supervisor",emp_mob:"4426188660",emp_date:"Jan 1, 2020", emp_manager:""},
{id:244,pfp:icon_employee_profile,emp_id:"174",emp_name:"Viviana Lipson",emp_mail:"vlipson6r@washington.edu",emp_role:"Project Manager",emp_mob:"0423088971",emp_date:"Jan 1, 2020", emp_manager:""},
{id:245,pfp:icon_employee_profile,emp_id:"38",emp_name:"Daryn Stienham",emp_mail:"dstienham6s@wp.com",emp_role:"Construction Worker",emp_mob:"8152479705",emp_date:"Jan 1, 2020", emp_manager:""},
{id:246,pfp:icon_employee_profile,emp_id:"101",emp_name:"Haydon Streatley",emp_mail:"hstreatley6t@posterous.com",emp_role:"Project Manager",emp_mob:"7870132950",emp_date:"Jan 1, 2020", emp_manager:""},
{id:247,pfp:icon_employee_profile,emp_id:"274",emp_name:"Maddy Lazare",emp_mail:"mlazare6u@rediff.com",emp_role:"Supervisor",emp_mob:"6150075001",emp_date:"Jan 1, 2020", emp_manager:""},
{id:248,pfp:icon_employee_profile,emp_id:"258",emp_name:"Robenia Plaister",emp_mail:"rplaister6v@deliciousdays.com",emp_role:"Estimator",emp_mob:"8651038461",emp_date:"Jan 1, 2020", emp_manager:""},
{id:249,pfp:icon_employee_profile,emp_id:"76",emp_name:"Tamas Lightbourn",emp_mail:"tlightbourn6w@studiopress.com",emp_role:"Estimator",emp_mob:"3992700615",emp_date:"Jan 1, 2020", emp_manager:""},
{id:250,pfp:icon_employee_profile,emp_id:"42",emp_name:"Ricky Rowthorne",emp_mail:"rrowthorne6x@squidoo.com",emp_role:"Construction Worker",emp_mob:"3410426027",emp_date:"Jan 1, 2020", emp_manager:""},
{id:251,pfp:icon_employee_profile,emp_id:"82",emp_name:"Merridie Esche",emp_mail:"mesche6y@diigo.com",emp_role:"Construction Expeditor",emp_mob:"2892687411",emp_date:"Jan 1, 2020", emp_manager:""},
{id:252,pfp:icon_employee_profile,emp_id:"254",emp_name:"Charil Dozdill",emp_mail:"cdozdill6z@si.edu",emp_role:"Engineer",emp_mob:"1553857550",emp_date:"Jan 1, 2020", emp_manager:""},
{id:253,pfp:icon_employee_profile,emp_id:"272",emp_name:"Mariam Dermott",emp_mail:"mdermott70@aboutads.info",emp_role:"Project Manager",emp_mob:"4100965850",emp_date:"Jan 1, 2020", emp_manager:""},
{id:254,pfp:icon_employee_profile,emp_id:"158",emp_name:"Dominique Overill",emp_mail:"doverill71@mapquest.com",emp_role:"Engineer",emp_mob:"3636910302",emp_date:"Jan 1, 2020", emp_manager:""},
{id:255,pfp:icon_employee_profile,emp_id:"176",emp_name:"Josephine McMeeking",emp_mail:"jmcmeeking72@miitbeian.gov.cn",emp_role:"Estimator",emp_mob:"2645323766",emp_date:"Jan 1, 2020", emp_manager:""},
{id:256,pfp:icon_employee_profile,emp_id:"110",emp_name:"Judon Dechelette",emp_mail:"jdechelette73@marriott.com",emp_role:"Construction Worker",emp_mob:"0617620830",emp_date:"Jan 1, 2020", emp_manager:""},
{id:257,pfp:icon_employee_profile,emp_id:"125",emp_name:"Cyril Scarsbrook",emp_mail:"cscarsbrook74@networksolutions.com",emp_role:"Estimator",emp_mob:"4709654158",emp_date:"Jan 1, 2020", emp_manager:""},
{id:258,pfp:icon_employee_profile,emp_id:"224",emp_name:"Reagen Brister",emp_mail:"rbrister75@ifeng.com",emp_role:"Architect",emp_mob:"4111217753",emp_date:"Jan 1, 2020", emp_manager:""},
{id:259,pfp:icon_employee_profile,emp_id:"166",emp_name:"Henderson Woodage",emp_mail:"hwoodage76@bloglines.com",emp_role:"Construction Worker",emp_mob:"0050190229",emp_date:"Jan 1, 2020", emp_manager:""},
{id:260,pfp:icon_employee_profile,emp_id:"195",emp_name:"Culley Lundie",emp_mail:"clundie77@independent.co.uk",emp_role:"Surveyor",emp_mob:"1792532296",emp_date:"Jan 1, 2020", emp_manager:""},
{id:261,pfp:icon_employee_profile,emp_id:"190",emp_name:"Lars Ing",emp_mail:"ling78@google.pl",emp_role:"Subcontractor",emp_mob:"9654505401",emp_date:"Jan 1, 2020", emp_manager:""},
{id:262,pfp:icon_employee_profile,emp_id:"221",emp_name:"Shem Schiementz",emp_mail:"sschiementz79@bbb.org",emp_role:"Construction Manager",emp_mob:"0181534517",emp_date:"Jan 1, 2020", emp_manager:""},
{id:263,pfp:icon_employee_profile,emp_id:"164",emp_name:"Muire Leadstone",emp_mail:"mleadstone7a@4shared.com",emp_role:"Construction Foreman",emp_mob:"6216019775",emp_date:"Jan 1, 2020", emp_manager:""},
{id:264,pfp:icon_employee_profile,emp_id:"37",emp_name:"Rae Scroxton",emp_mail:"rscroxton7b@illinois.edu",emp_role:"Estimator",emp_mob:"7152521514",emp_date:"Jan 1, 2020", emp_manager:""},
{id:265,pfp:icon_employee_profile,emp_id:"231",emp_name:"Shannan Rucklidge",emp_mail:"srucklidge7c@hao123.com",emp_role:"Estimator",emp_mob:"4355284387",emp_date:"Jan 1, 2020", emp_manager:""},
{id:266,pfp:icon_employee_profile,emp_id:"137",emp_name:"Jacobo Sullens",emp_mail:"jsullens7d@mail.ru",emp_role:"Construction Foreman",emp_mob:"1177536099",emp_date:"Jan 1, 2020", emp_manager:""},
{id:267,pfp:icon_employee_profile,emp_id:"119",emp_name:"Irene Spadotto",emp_mail:"ispadotto7e@1688.com",emp_role:"Electrician",emp_mob:"0543535401",emp_date:"Jan 1, 2020", emp_manager:""},
{id:268,pfp:icon_employee_profile,emp_id:"126",emp_name:"Heinrick Licquorish",emp_mail:"hlicquorish7f@theglobeandmail.com",emp_role:"Architect",emp_mob:"2419992652",emp_date:"Jan 1, 2020", emp_manager:""},
{id:269,pfp:icon_employee_profile,emp_id:"215",emp_name:"Magda Edmonson",emp_mail:"medmonson7g@posterous.com",emp_role:"Construction Worker",emp_mob:"3460976330",emp_date:"Jan 1, 2020", emp_manager:""},
{id:270,pfp:icon_employee_profile,emp_id:"38",emp_name:"Dominique Munton",emp_mail:"dmunton7h@digg.com",emp_role:"Supervisor",emp_mob:"3838471679",emp_date:"Jan 1, 2020", emp_manager:""},
{id:271,pfp:icon_employee_profile,emp_id:"119",emp_name:"Adora Micklewright",emp_mail:"amicklewright7i@bigcartel.com",emp_role:"Architect",emp_mob:"8321806228",emp_date:"Jan 1, 2020", emp_manager:""},
{id:272,pfp:icon_employee_profile,emp_id:"220",emp_name:"Darb Angelo",emp_mail:"dangelo7j@topsy.com",emp_role:"Project Manager",emp_mob:"3669534105",emp_date:"Jan 1, 2020", emp_manager:""},
{id:273,pfp:icon_employee_profile,emp_id:"74",emp_name:"Cointon Pirozzi",emp_mail:"cpirozzi7k@e-recht24.de",emp_role:"Construction Worker",emp_mob:"5627723386",emp_date:"Jan 1, 2020", emp_manager:""},
{id:274,pfp:icon_employee_profile,emp_id:"229",emp_name:"Livy Martel",emp_mail:"lmartel7l@princeton.edu",emp_role:"Construction Worker",emp_mob:"7825021061",emp_date:"Jan 1, 2020", emp_manager:""},
{id:275,pfp:icon_employee_profile,emp_id:"279",emp_name:"Kiley Blaszczak",emp_mail:"kblaszczak7m@earthlink.net",emp_role:"Construction Manager",emp_mob:"2797213254",emp_date:"Jan 1, 2020", emp_manager:""},
{id:276,pfp:icon_employee_profile,emp_id:"105",emp_name:"Noelle Swalowe",emp_mail:"nswalowe7n@angelfire.com",emp_role:"Construction Expeditor",emp_mob:"0821233327",emp_date:"Jan 1, 2020", emp_manager:""},
{id:277,pfp:icon_employee_profile,emp_id:"91",emp_name:"Leroi Rountree",emp_mail:"lrountree7o@ucsd.edu",emp_role:"Construction Manager",emp_mob:"1096736128",emp_date:"Jan 1, 2020", emp_manager:""},
{id:278,pfp:icon_employee_profile,emp_id:"235",emp_name:"Barnie Jaze",emp_mail:"bjaze7p@i2i.jp",emp_role:"Construction Manager",emp_mob:"4555118456",emp_date:"Jan 1, 2020", emp_manager:""},
{id:279,pfp:icon_employee_profile,emp_id:"129",emp_name:"Gabriell Greenstreet",emp_mail:"ggreenstreet7q@ning.com",emp_role:"Construction Worker",emp_mob:"4927911578",emp_date:"Jan 1, 2020", emp_manager:""},
{id:280,pfp:icon_employee_profile,emp_id:"199",emp_name:"Dory Guilaem",emp_mail:"dguilaem7r@de.vu",emp_role:"Project Manager",emp_mob:"4212215942",emp_date:"Jan 1, 2020", emp_manager:""},
{id:281,pfp:icon_employee_profile,emp_id:"168",emp_name:"Garv Jerzyk",emp_mail:"gjerzyk7s@hubpages.com",emp_role:"Estimator",emp_mob:"8744110383",emp_date:"Jan 1, 2020", emp_manager:""},
{id:282,pfp:icon_employee_profile,emp_id:"77",emp_name:"Coop Reasce",emp_mail:"creasce7t@woothemes.com",emp_role:"Architect",emp_mob:"5671975255",emp_date:"Jan 1, 2020", emp_manager:""},
{id:283,pfp:icon_employee_profile,emp_id:"25",emp_name:"Carmelina De Gregario",emp_mail:"cde7u@opera.com",emp_role:"Surveyor",emp_mob:"1035402742",emp_date:"Jan 1, 2020", emp_manager:""},
{id:284,pfp:icon_employee_profile,emp_id:"76",emp_name:"Ilyse Cobson",emp_mail:"icobson7v@qq.com",emp_role:"Engineer",emp_mob:"5786654494",emp_date:"Jan 1, 2020", emp_manager:""},
{id:285,pfp:icon_employee_profile,emp_id:"26",emp_name:"Andromache Smelley",emp_mail:"asmelley7w@wikipedia.org",emp_role:"Construction Manager",emp_mob:"2629601730",emp_date:"Jan 1, 2020", emp_manager:""},
{id:286,pfp:icon_employee_profile,emp_id:"280",emp_name:"Tobe Gautrey",emp_mail:"tgautrey7x@indiegogo.com",emp_role:"Supervisor",emp_mob:"3856611797",emp_date:"Jan 1, 2020", emp_manager:""},
{id:287,pfp:icon_employee_profile,emp_id:"39",emp_name:"Terencio Chaikovski",emp_mail:"tchaikovski7y@wikia.com",emp_role:"Construction Expeditor",emp_mob:"7701944001",emp_date:"Jan 1, 2020", emp_manager:""},
{id:288,pfp:icon_employee_profile,emp_id:"105",emp_name:"Barthel Law",emp_mail:"blaw7z@ebay.co.uk",emp_role:"Construction Worker",emp_mob:"4120179222",emp_date:"Jan 1, 2020", emp_manager:""},
{id:289,pfp:icon_employee_profile,emp_id:"203",emp_name:"Randy Galliford",emp_mail:"rgalliford80@ebay.co.uk",emp_role:"Engineer",emp_mob:"4128547158",emp_date:"Jan 1, 2020", emp_manager:""},
{id:290,pfp:icon_employee_profile,emp_id:"58",emp_name:"Karilynn Burger",emp_mail:"kburger81@vkontakte.ru",emp_role:"Engineer",emp_mob:"2513186990",emp_date:"Jan 1, 2020", emp_manager:""},
{id:291,pfp:icon_employee_profile,emp_id:"8",emp_name:"Rodge Preble",emp_mail:"rpreble82@nationalgeographic.com",emp_role:"Construction Worker",emp_mob:"6128123333",emp_date:"Jan 1, 2020", emp_manager:""},
{id:292,pfp:icon_employee_profile,emp_id:"21",emp_name:"Lamont Haycock",emp_mail:"lhaycock83@trellian.com",emp_role:"Electrician",emp_mob:"6791169486",emp_date:"Jan 1, 2020", emp_manager:""},
{id:293,pfp:icon_employee_profile,emp_id:"238",emp_name:"Adelle Diano",emp_mail:"adiano84@1688.com",emp_role:"Estimator",emp_mob:"8406516666",emp_date:"Jan 1, 2020", emp_manager:""},
{id:294,pfp:icon_employee_profile,emp_id:"211",emp_name:"Jacintha Jedrych",emp_mail:"jjedrych85@etsy.com",emp_role:"Estimator",emp_mob:"1350930636",emp_date:"Jan 1, 2020", emp_manager:""},
{id:295,pfp:icon_employee_profile,emp_id:"91",emp_name:"Kelcy Vasenin",emp_mail:"kvasenin86@princeton.edu",emp_role:"Construction Expeditor",emp_mob:"5212636876",emp_date:"Jan 1, 2020", emp_manager:""},
{id:296,pfp:icon_employee_profile,emp_id:"250",emp_name:"Herrick Mohring",emp_mail:"hmohring87@mac.com",emp_role:"Subcontractor",emp_mob:"4645469576",emp_date:"Jan 1, 2020", emp_manager:""},
{id:297,pfp:icon_employee_profile,emp_id:"268",emp_name:"Sheelagh Webber",emp_mail:"swebber88@gizmodo.com",emp_role:"Construction Expeditor",emp_mob:"1098856104",emp_date:"Jan 1, 2020", emp_manager:""},
{id:298,pfp:icon_employee_profile,emp_id:"248",emp_name:"Lois Barniss",emp_mail:"lbarniss89@newyorker.com",emp_role:"Construction Expeditor",emp_mob:"3614400662",emp_date:"Jan 1, 2020", emp_manager:""},
{id:299,pfp:icon_employee_profile,emp_id:"255",emp_name:"Caprice Hatwells",emp_mail:"chatwells8a@washington.edu",emp_role:"Surveyor",emp_mob:"2981742671",emp_date:"Jan 1, 2020", emp_manager:""},
{id:300,pfp:icon_employee_profile,emp_id:"189",emp_name:"Sherri Silbersak",emp_mail:"ssilbersak8b@bloglovin.com",emp_role:"Construction Manager",emp_mob:"8158785727",emp_date:"Jan 1, 2020", emp_manager:""}]

export default EmployeeCardList;