import icon_employee_profile from "../../assets/images/employees/icon_employee_profile.png"

const EmployeeCardList = [
    {
        id:1,
        pfp: icon_employee_profile,
        emp_id: "103",
        emp_name: "Bernardo Galavis",
        emp_mail: "bernardo.g@piktorlabs.com",
        emp_role: "Web Developer",
        emp_mob: "9876323210",
        emp_date: "Jan 1, 2020",
    },
    {
        id:2,
        pfp: icon_employee_profile,
        emp_id: "102",
        emp_name: "Ruby Pen",
        emp_mail: "Ruby.p@piktorlabs.com",
        emp_role: "Front End Developer",
        emp_mob: "9876123210",
        emp_date: "Jan 1, 2020",
    },
    {
        id:3,
        pfp: icon_employee_profile,
        emp_id: "101",
        emp_name: "Theon Grey",
        emp_mail: "Grey.theon@piktorlabs.com",
        emp_role: "UX Designer",
        emp_mob: "1376543210",
        emp_date: "Jan 1, 2020",
    },
    {
        id:4,
        pfp: icon_employee_profile,
        emp_id: "100",
        emp_name: "Ariana Grande",
        emp_mail: "Ariana.g@piktorlabs.com",
        emp_role: "Data Scientist",
        emp_mob: "9876543210",
        emp_date: "Jan 1, 2020",
    },
    {
        id:5,
        pfp: icon_employee_profile,
        emp_id: "99",
        emp_name: "Emma Watson",
        emp_mail: "Emma@piktorlabs.com",
        emp_role: "Product Manager",
        emp_mob: "9876509210",
        emp_date: "Jan 1, 2020",
    },
    {
        id:6,
        pfp: icon_employee_profile,
        emp_id: "98",
        emp_name: "Rebecca James",
        emp_mail: "Rebeccajames@piktorlabs.com",
        emp_role: "Interaction Designer",
        emp_mob: "9828543210",
        emp_date: "Jan 1, 2020",
    },
    {
        id:7,
        pfp: icon_employee_profile,
        emp_id: "97",
        emp_name: "Tania Rai",
        emp_mail: "Tania@piktorlabs.com",
        emp_role: "Data Analyst",
        emp_mob: "9666543210",
        emp_date: "Jan 1, 2020",
    },
    {
        id:8,
        pfp: icon_employee_profile,
        emp_id: "96",
        emp_name: "Thomas Green",
        emp_mail: "Thomasgreen@piktorlabs.com",
        emp_role: "Software Engineer",
        emp_mob: "9876543210",
        emp_date: "Jan 1, 2020",
    },
    {
        id:9,
        pfp: icon_employee_profile,
        emp_id: "95",
        emp_name: "Emily Clarke",
        emp_mail: "Emily clarke@piktorlabs.com",
        emp_role: "Web Developer",
        emp_mob: "3476543210",
        emp_date: "Jan 1, 2020",
    },
    {
        id:10,
        pfp: icon_employee_profile,
        emp_id: "94",
        emp_name: "Summer Simpson",
        emp_mail: "Summersimpsons@piktorlabs.com",
        emp_role: "Web Developer",
        emp_mob: "5676543210",
        emp_date: "Jan 1, 2020",
    },
    {
        id:11,
        pfp: icon_employee_profile,
        emp_id: "93",
        emp_name: "James White",
        emp_mail: "James.w@piktorlabs.com",
        emp_role: "Web Developer",
        emp_mob: "1236543210",
        emp_date: "Jan 1, 2020",
    },
    {
        id:12,
        pfp: icon_employee_profile,
        emp_id: "92",
        emp_name: "Bernardo Galavis",
        emp_mail: "bernardo.g@piktorlabs.com",
        emp_role: "Web Developer",
        emp_mob: "9996543210",
        emp_date: "Jan 1, 2020",
    },
    {
        id:13,
        pfp: icon_employee_profile,
        emp_id: "91",
        emp_name: "Ruby Pen",
        emp_mail: "Ruby.p@piktorlabs.com",
        emp_role: "Front End Developer",
        emp_mob: "9876543210",
        emp_date: "Jan 1, 2020",
    },
    {
        id:14,
        pfp: icon_employee_profile,
        emp_id: "90",
        emp_name: "Theon Grey",
        emp_mail: "Grey.theon@piktorlabs.com",
        emp_role: "UX Designer",
        emp_mob: "9876543210",
        emp_date: "Jan 1, 2020",
    },
    {
        id:15,
        pfp: icon_employee_profile,
        emp_id: "89",
        emp_name: "Ariana Grande",
        emp_mail: "Ariana.g@piktorlabs.com",
        emp_role: "Data Scientist",
        emp_mob: "9876543210",
        emp_date: "Jan 1, 2020",
    },
    {
        id:16,
        pfp: icon_employee_profile,
        emp_id: "88",
        emp_name: "Emma Watson",
        emp_mail: "Emma@piktorlabs.com",
        emp_role: "Product Manager",
        emp_mob: "9876543210",
        emp_date: "Jan 1, 2020",
    },
    {
        id:17,
        pfp: icon_employee_profile,
        emp_id: "87",
        emp_name: "Rebecca James",
        emp_mail: "Rebeccajames@piktorlabs.com",
        emp_role: "Interaction Designer",
        emp_mob: "9876543210",
        emp_date: "Jan 1, 2020",
    },
    {
        id:18,
        pfp: icon_employee_profile,
        emp_id: "86",
        emp_name: "Tania Rai",
        emp_mail: "Tania@piktorlabs.com",
        emp_role: "Data Analyst",
        emp_mob: "9876543210",
        emp_date: "Jan 1, 2020",
    },
    {
        id:19,
        pfp: icon_employee_profile,
        emp_id: "85",
        emp_name: "Thomas Green",
        emp_mail: "Thomasgreen@piktorlabs.com",
        emp_role: "Software Engineer",
        emp_mob: "9876543210",
        emp_date: "Jan 1, 2020",
    },
    {
        id:20,
        pfp: icon_employee_profile,
        emp_id: "84",
        emp_name: "Emily Clarke",
        emp_mail: "Emily clarke@piktorlabs.com",
        emp_role: "Web Developer",
        emp_mob: "9876543210",
        emp_date: "Jan 1, 2020",
    },
    {
        id:21,
        pfp: icon_employee_profile,
        emp_id: "83",
        emp_name: "Summer Simpson",
        emp_mail: "Summersimpsons@piktorlabs.com",
        emp_role: "Web Developer",
        emp_mob: "9876543210",
        emp_date: "Jan 1, 2020",
    },
    {
        id:22,
        pfp: icon_employee_profile,
        emp_id: "82",
        emp_name: "James White",
        emp_mail: "James.w@piktorlabs.com",
        emp_role: "Web Developer",
        emp_mob: "9876543210",
        emp_date: "Jan 1, 2020",
    },
    {
        id:23,
        pfp: icon_employee_profile,
        emp_id: "81",
        emp_name: "Bernardo Galavis",
        emp_mail: "bernardo.g@piktorlabs.com",
        emp_role: "Web Developer",
        emp_mob: "9876543210",
        emp_date: "Jan 1, 2020",
    },
    {
        id:24,
        pfp: icon_employee_profile,
        emp_id: "80",
        emp_name: "Ruby Pen",
        emp_mail: "Ruby.p@piktorlabs.com",
        emp_role: "Front End Developer",
        emp_mob: "9876543210",
        emp_date: "Jan 1, 2020",
    },
    {
        id:25,
        pfp: icon_employee_profile,
        emp_id: "79",
        emp_name: "Theon Grey",
        emp_mail: "Grey.theon@piktorlabs.com",
        emp_role: "UX Designer",
        emp_mob: "9876543210",
        emp_date: "Jan 1, 2020",
    },
    {
        id:26,
        pfp: icon_employee_profile,
        emp_id: "78",
        emp_name: "Ariana Grande",
        emp_mail: "Ariana.g@piktorlabs.com",
        emp_role: "Data Scientist",
        emp_mob: "9876543210",
        emp_date: "Jan 1, 2020",
    },
    {
        id:27,
        pfp: icon_employee_profile,
        emp_id: "77",
        emp_name: "Emma Watson",
        emp_mail: "Emma@piktorlabs.com",
        emp_role: "Product Manager",
        emp_mob: "9876543210",
        emp_date: "Jan 1, 2020",
    },
    {
        id:28,
        pfp: icon_employee_profile,
        emp_id: "76",
        emp_name: "Rebecca James",
        emp_mail: "Rebeccajames@piktorlabs.com",
        emp_role: "Interaction Designer",
        emp_mob: "9876543210",
        emp_date: "Jan 1, 2020",
    },
    {
        id:29,
        pfp: icon_employee_profile,
        emp_id: "75",
        emp_name: "Tania Rai",
        emp_mail: "Tania@piktorlabs.com",
        emp_role: "Data Analyst",
        emp_mob: "9876543210",
        emp_date: "Jan 1, 2020",
    },
    {
        id:30,
        pfp: icon_employee_profile,
        emp_id: "74",
        emp_name: "Thomas Green",
        emp_mail: "Thomasgreen@piktorlabs.com",
        emp_role: "Software Engineer",
        emp_mob: "9876543210",
        emp_date: "Jan 1, 2020",
    },
    {
        id:31,
        pfp: icon_employee_profile,
        emp_id: "73",
        emp_name: "Emily Clarke",
        emp_mail: "Emily clarke@piktorlabs.com",
        emp_role: "Web Developer",
        emp_mob: "9876543210",
        emp_date: "Jan 1, 2020",
    },
    {
        id:32,
        pfp: icon_employee_profile,
        emp_id: "72",
        emp_name: "Summer Simpson",
        emp_mail: "Summersimpsons@piktorlabs.com",
        emp_role: "Web Developer",
        emp_mob: "9876543210",
        emp_date: "Jan 1, 2020",
    },
    {
        id:33,
        pfp: icon_employee_profile,
        emp_id: "71",
        emp_name: "James White",
        emp_mail: "James.w@piktorlabs.com",
        emp_role: "Web Developer",
        emp_mob: "9876543210",
        emp_date: "Jan 1, 2020",
    },
    {
        id:34,
        pfp: icon_employee_profile,
        emp_id: "70",
        emp_name: "Bernardo Galavis",
        emp_mail: "bernardo.g@piktorlabs.com",
        emp_role: "Web Developer",
        emp_mob: "9876543210",
        emp_date: "Jan 1, 2020",
    },
    {
        id:35,
        pfp: icon_employee_profile,
        emp_id: "69",
        emp_name: "Ruby Pen",
        emp_mail: "Ruby.p@piktorlabs.com",
        emp_role: "Front End Developer",
        emp_mob: "9876543210",
        emp_date: "Jan 1, 2020",
    },
    {
        id:36,
        pfp: icon_employee_profile,
        emp_id: "68",
        emp_name: "Theon Grey",
        emp_mail: "Grey.theon@piktorlabs.com",
        emp_role: "UX Designer",
        emp_mob: "9876543210",
        emp_date: "Jan 1, 2020",
    },
    {
        id:37,
        pfp: icon_employee_profile,
        emp_id: "67",
        emp_name: "Ariana Grande",
        emp_mail: "Ariana.g@piktorlabs.com",
        emp_role: "Data Scientist",
        emp_mob: "9876543210",
        emp_date: "Jan 1, 2020",
    },
    {
        id:38,
        pfp: icon_employee_profile,
        emp_id: "66",
        emp_name: "Emma Watson",
        emp_mail: "Emma@piktorlabs.com",
        emp_role: "Product Manager",
        emp_mob: "9876543210",
        emp_date: "Jan 1, 2020",
    },
    {
        id:39,
        pfp: icon_employee_profile,
        emp_id: "65",
        emp_name: "Rebecca James",
        emp_mail: "Rebeccajames@piktorlabs.com",
        emp_role: "Interaction Designer",
        emp_mob: "9876543210",
        emp_date: "Jan 1, 2020",
    },
    {
        id:40,
        pfp: icon_employee_profile,
        emp_id: "64",
        emp_name: "Tania Rai",
        emp_mail: "Tania@piktorlabs.com",
        emp_role: "Data Analyst",
        emp_mob: "9876543210",
        emp_date: "Jan 1, 2020",
    },
    {
        id:41,
        pfp: icon_employee_profile,
        emp_id: "63",
        emp_name: "Thomas Green",
        emp_mail: "Thomasgreen@piktorlabs.com",
        emp_role: "Software Engineer",
        emp_mob: "9876543210",
        emp_date: "Jan 1, 2020",
    },
    {
        id:42,
        pfp: icon_employee_profile,
        emp_id: "62",
        emp_name: "Emily Clarke",
        emp_mail: "Emily clarke@piktorlabs.com",
        emp_role: "Web Developer",
        emp_mob: "9876543210",
        emp_date: "Jan 1, 2020",
    },
    {
        id:43,
        pfp: icon_employee_profile,
        emp_id: "61",
        emp_name: "Summer Simpson",
        emp_mail: "Summersimpsons@piktorlabs.com",
        emp_role: "Web Developer",
        emp_mob: "9876543210",
        emp_date: "Jan 1, 2020",
    },
    {
        id:44,
        pfp: icon_employee_profile,
        emp_id: "60",
        emp_name: "James White",
        emp_mail: "James.w@piktorlabs.com",
        emp_role: "Web Developer",
        emp_mob: "9876543210",
        emp_date: "Jan 1, 2020",
    },
    {
        id:45,
        pfp: icon_employee_profile,
        emp_id: "59",
        emp_name: "Bernardo Galavis",
        emp_mail: "bernardo.g@piktorlabs.com",
        emp_role: "Web Developer",
        emp_mob: "9876543210",
        emp_date: "Jan 1, 2020",
    },
    {
        id:46,
        pfp: icon_employee_profile,
        emp_id: "58",
        emp_name: "Ruby Pen",
        emp_mail: "Ruby.p@piktorlabs.com",
        emp_role: "Front End Developer",
        emp_mob: "9876543210",
        emp_date: "Jan 1, 2020",
    },
    {
        id:47,
        pfp: icon_employee_profile,
        emp_id: "57",
        emp_name: "Theon Grey",
        emp_mail: "Grey.theon@piktorlabs.com",
        emp_role: "UX Designer",
        emp_mob: "9876543210",
        emp_date: "Jan 1, 2020",
    },
    {
        id:48,
        pfp: icon_employee_profile,
        emp_id: "56",
        emp_name: "Ariana Grande",
        emp_mail: "Ariana.g@piktorlabs.com",
        emp_role: "Data Scientist",
        emp_mob: "9876543210",
        emp_date: "Jan 1, 2020",
    },
    {
        id:49,
        pfp: icon_employee_profile,
        emp_id: "55",
        emp_name: "Emma Watson",
        emp_mail: "Emma@piktorlabs.com",
        emp_role: "Product Manager",
        emp_mob: "9876543210",
        emp_date: "Jan 1, 2020",
    },
    {
        id:50,
        pfp: icon_employee_profile,
        emp_id: "54",
        emp_name: "Rebecca James",
        emp_mail: "Rebeccajames@piktorlabs.com",
        emp_role: "Interaction Designer",
        emp_mob: "9876543210",
        emp_date: "Jan 1, 2020",
    },
    {
        id:51,
        pfp: icon_employee_profile,
        emp_id: "53",
        emp_name: "Tania Rai",
        emp_mail: "Tania@piktorlabs.com",
        emp_role: "Data Analyst",
        emp_mob: "9876543210",
        emp_date: "Jan 1, 2020",
    },
    {
        id:52,
        pfp: icon_employee_profile,
        emp_id: "52",
        emp_name: "Thomas Green",
        emp_mail: "Thomasgreen@piktorlabs.com",
        emp_role: "Software Engineer",
        emp_mob: "9876543210",
        emp_date: "Jan 1, 2020",
    },
    {
        id:53,
        pfp: icon_employee_profile,
        emp_id: "51",
        emp_name: "Emily Clarke",
        emp_mail: "Emily clarke@piktorlabs.com",
        emp_role: "Web Developer",
        emp_mob: "9876543210",
        emp_date: "Jan 1, 2020",
    },
    {
        id:54,
        pfp: icon_employee_profile,
        emp_id: "50",
        emp_name: "Summer Simpson",
        emp_mail: "Summersimpsons@piktorlabs.com",
        emp_role: "Web Developer",
        emp_mob: "9876543210",
        emp_date: "Jan 1, 2020",
    },
    {
        id:55,
        pfp: icon_employee_profile,
        emp_id: "49",
        emp_name: "James White",
        emp_mail: "James.w@piktorlabs.com",
        emp_role: "Web Developer",
        emp_mob: "9876543210",
        emp_date: "Jan 1, 2020",
    },

];

export default EmployeeCardList;