import icon_attendee from "../../assets/images/dashboard/icon_attendee.png";

const ExpenseList = [
    {
        id:1,
        icon: icon_attendee,
        emp: "#12",
        name: "Theon Grey",
        dates: "17th, Oct",
        comments: "Travelhome",
    },
    {
        id:2,
        icon: icon_attendee,
        emp: "#14",
        name: "Rani",
        dates: "5th, Oct",
        comments: "Travelling",
    },
    {
        id:3,
        icon: icon_attendee,
        emp: "#104",
        name: "Meerta",
        dates: "25th, Sept",
        comments: "Travelling to home town",
    },
    {
        id:4,
        icon: icon_attendee,
        emp: "#107",
        name: "Anjana",
        dates: "21st, Sept",
        comments: "Travelling",
    },
    {
        id:5,
        icon: icon_attendee,
        emp: "#13",
        name: "Thomas Wells",
        dates: "21st, Sept",
        comments: "Travelling",
    },
    {
        id:6,
        icon: icon_attendee,
        emp: "#44",
        name: "Eber",
        dates: "5th, Sept",
        comments: "Travelling",
    },
    {
        id:7,
        icon: icon_attendee,
        emp: "#12",
        name: "Theon Grey",
        dates: "17th, Oct",
        comments: "Travelhome",
    },
    {
        id:8,
        icon: icon_attendee,
        emp: "#14",
        name: "Rani",
        dates: "5th, Oct",
        comments: "Travelling",
    },
    {
        id:9,
        icon: icon_attendee,
        emp: "#104",
        name: "Meerta",
        dates: "25th, Sept",
        comments: "Travelling to home town",
    },
    {
        id:10,
        icon: icon_attendee,
        emp: "#107",
        name: "Anjana",
        dates: "21st, Sept",
        comments: "Travelling",
    },
    {
        id:11,
        icon: icon_attendee,
        emp: "#13",
        name: "Thomas Wells",
        dates: "21st, Sept",
        comments: "Travelling",
    },
    {
        id:12,
        icon: icon_attendee,
        emp: "#44",
        name: "Eber",
        dates: "5th, Sept",
        comments: "Travelling",
    },
];

export default ExpenseList;